"""Qwen3 flash attention shader."""

from __future__ import annotations

from torch2vk.copied_shader_source import copied_shader_variant_source
from torch2vk.shader import (
    Binding,
    BindingAccess,
    PushConstantBlock,
    PushConstantField,
    ShaderContract,
    ShaderVariant,
    TensorContract,
)

FLASH_ATTN_F32_F16 = ShaderVariant(
    name="flash_attn_f32_f16_aligned_f32accf16",
    family="flash_attention",
    contract=ShaderContract(
        name="flash_attn_f32_f16_aligned_f32accf16",
        inputs={
            "q": TensorContract(dtype="float32", shape=("B", "S", "QH", "D")),
            "k": TensorContract(dtype="float16", shape=("B", "T", "KH", "D")),
            "v": TensorContract(dtype="float16", shape=("B", "T", "KH", "D")),
            "mask": TensorContract(dtype="float16", shape=("B", 1, "S", "T")),
            "sinks_placeholder": TensorContract(dtype="float32", shape=("B", "S", "QH", "D")),
            "mask_opt_placeholder": TensorContract(dtype="float32", shape=("B", "S", "QH", "D")),
        },
        outputs={"split_k_output": TensorContract(dtype="float32", shape=("SK",))},
        bindings=(
            Binding("q", 0, BindingAccess.READ),
            Binding("k", 1, BindingAccess.READ),
            Binding("v", 2, BindingAccess.READ),
            Binding("mask", 3, BindingAccess.READ),
            Binding("sinks_placeholder", 4, BindingAccess.READ),
            Binding("split_k_output", 5, BindingAccess.WRITE),
            Binding("mask_opt_placeholder", 6, BindingAccess.READ),
        ),
        dispatch=("S*4", "KH", "B"),
        push_constants=PushConstantBlock(
            size=128,
            fields=(
                PushConstantField("N", 0, "uint32", "S"),
                PushConstantField("KV", 4, "uint32", "T"),
                PushConstantField("ne1", 8, "uint32", "QH"),
                PushConstantField("ne2", 12, "uint32", "S"),
                PushConstantField("ne3", 16, "uint32", "B"),
                PushConstantField("neq2", 20, "uint32", "QH"),
                PushConstantField("neq3", 24, "uint32", "B"),
                PushConstantField("nek2", 28, "uint32", "KH"),
                PushConstantField("nek3", 32, "uint32", "B"),
                PushConstantField("nev2", 36, "uint32", "KH"),
                PushConstantField("nev3", 40, "uint32", "B"),
                PushConstantField("nem1", 44, "uint32", "S"),
                PushConstantField("nem2", 48, "uint32", 1),
                PushConstantField("nem3", 52, "uint32", "B"),
                PushConstantField("nb01", 56, "uint32", "D"),
                PushConstantField("nb02", 60, "uint32", "D*QH*4"),
                PushConstantField("nb03", 64, "uint32", "D*QH*S*4"),
                PushConstantField("nb11", 68, "uint32", "D"),
                PushConstantField("nb12", 72, "uint32", "D*KH*2"),
                PushConstantField("nb13", 76, "uint32", "D*KH*T*2"),
                PushConstantField("nb21", 80, "uint32", "D"),
                PushConstantField("nb22", 84, "uint32", "D*KH*2"),
                PushConstantField("nb23", 88, "uint32", "D*KH*T*2"),
                PushConstantField("scale", 92, "float32", 0.08838834764831845),
                PushConstantField("max_bias", 96, "float32", 0.0),
                PushConstantField("logit_softcap", 100, "float32", 0.0),
                PushConstantField("mask_n_head_log2", 104, "uint32", 1),
                PushConstantField("m0", 108, "float32", 0.0),
                PushConstantField("m1", 112, "float32", 0.0),
                PushConstantField("gqa_ratio", 116, "uint32", 1),
                PushConstantField("split_kv", 120, "uint32", 4),
                PushConstantField("k_num", 124, "uint32", 4),
            ),
        ),
    ),
    specialization_constants={
        0: 256,
        1: 16,
        2: 64,
        3: 128,
        4: 128,
        5: 0,
        6: 8,
        7: 4,
        8: 64,
        9: 0,
        10: 2,
        11: 0,
    },
    compile_defines=(
        "ACC_TYPE=float",
        "ACC_TYPEV2=vec2",
        "ACC_TYPEV4=vec4",
        "COOPMAT=1",
        "D_TYPE=float",
        "D_TYPEV4=vec4",
        "FLOAT16=1",
        "FLOAT_TYPE=float16_t",
        "FLOAT_TYPEV2=f16vec2",
        "FLOAT_TYPEV4=f16vec4",
        "FLOAT_TYPE_MAX=float16_t(65504.0)",
        "Q_TYPE=float",
    ),
    source=copied_shader_variant_source(
        "flash_attn_f32_f16_aligned_f32accf16.py",
        "FLASH_ATTN_F32_F16_ALIGNED_F32ACCF16",
    ),
)
