"""Generated shader index."""

from models.exported_omnivoice.shaders.add_f32 import ADD_F32  # noqa: F401
from models.exported_omnivoice.shaders.add_f32_37 import ADD_F32_37  # noqa: F401
from models.exported_omnivoice.shaders.add_f32_43 import ADD_F32_43  # noqa: F401
from models.exported_omnivoice.shaders.add_scalar import ADD_SCALAR  # noqa: F401
from models.exported_omnivoice.shaders.add_scalar_17 import ADD_SCALAR_17  # noqa: F401
from models.exported_omnivoice.shaders.add_scalar_9 import ADD_SCALAR_9  # noqa: F401
from models.exported_omnivoice.shaders.audio_head_linear_nobias_f32 import AUDIO_HEAD_LINEAR_NOBIAS_F32  # noqa: F401
from models.exported_omnivoice.shaders.cat_f32 import CAT_F32  # noqa: F401
from models.exported_omnivoice.shaders.cat_f32_32 import CAT_F32_32  # noqa: F401
from models.exported_omnivoice.shaders.linear_nobias_f32 import LINEAR_NOBIAS_F32  # noqa: F401
from models.exported_omnivoice.shaders.linear_nobias_f32_14 import LINEAR_NOBIAS_F32_14  # noqa: F401
from models.exported_omnivoice.shaders.linear_nobias_f32_22 import LINEAR_NOBIAS_F32_22  # noqa: F401
from models.exported_omnivoice.shaders.linear_nobias_f32_36 import LINEAR_NOBIAS_F32_36  # noqa: F401
from models.exported_omnivoice.shaders.linear_nobias_f32_38 import LINEAR_NOBIAS_F32_38  # noqa: F401
from models.exported_omnivoice.shaders.linear_nobias_f32_40 import LINEAR_NOBIAS_F32_40  # noqa: F401
from models.exported_omnivoice.shaders.linear_nobias_f32_42 import LINEAR_NOBIAS_F32_42  # noqa: F401
from models.exported_omnivoice.shaders.mean_dim_f32 import MEAN_DIM_F32  # noqa: F401
from models.exported_omnivoice.shaders.mean_dim_f32_16 import MEAN_DIM_F32_16  # noqa: F401
from models.exported_omnivoice.shaders.mean_dim_f32_8 import MEAN_DIM_F32_8  # noqa: F401
from models.exported_omnivoice.shaders.mul_broadcast_inner import MUL_BROADCAST_INNER  # noqa: F401
from models.exported_omnivoice.shaders.mul_broadcast_inner_29 import MUL_BROADCAST_INNER_29  # noqa: F401
from models.exported_omnivoice.shaders.mul_broadcast_inner_33 import MUL_BROADCAST_INNER_33  # noqa: F401
from models.exported_omnivoice.shaders.mul_broadcast_last import MUL_BROADCAST_LAST  # noqa: F401
from models.exported_omnivoice.shaders.mul_broadcast_last_11 import MUL_BROADCAST_LAST_11  # noqa: F401
from models.exported_omnivoice.shaders.mul_broadcast_last_19 import MUL_BROADCAST_LAST_19  # noqa: F401
from models.exported_omnivoice.shaders.mul_f32 import MUL_F32  # noqa: F401
from models.exported_omnivoice.shaders.mul_left_broadcast import MUL_LEFT_BROADCAST  # noqa: F401
from models.exported_omnivoice.shaders.mul_left_broadcast_12 import MUL_LEFT_BROADCAST_12  # noqa: F401
from models.exported_omnivoice.shaders.mul_left_broadcast_20 import MUL_LEFT_BROADCAST_20  # noqa: F401
from models.exported_omnivoice.shaders.neg_f32 import NEG_F32  # noqa: F401
from models.exported_omnivoice.shaders.omnivoice_cfg_score_f32 import OMNIVOICE_CFG_SCORE_F32  # noqa: F401
from models.exported_omnivoice.shaders.omnivoice_input_embed_f32 import OMNIVOICE_INPUT_EMBED_F32  # noqa: F401
from models.exported_omnivoice.shaders.omnivoice_token_update_topk_f32 import OMNIVOICE_TOKEN_UPDATE_TOPK_F32  # noqa: F401
from models.exported_omnivoice.shaders.pow_scalar_f32 import POW_SCALAR_F32  # noqa: F401
from models.exported_omnivoice.shaders.pow_scalar_f32_15 import POW_SCALAR_F32_15  # noqa: F401
from models.exported_omnivoice.shaders.pow_scalar_f32_7 import POW_SCALAR_F32_7  # noqa: F401
from models.exported_omnivoice.shaders.rsqrt_f32 import RSQRT_F32  # noqa: F401
from models.exported_omnivoice.shaders.rsqrt_f32_10 import RSQRT_F32_10  # noqa: F401
from models.exported_omnivoice.shaders.rsqrt_f32_18 import RSQRT_F32_18  # noqa: F401
from models.exported_omnivoice.shaders.sdpa_masked_f32 import SDPA_MASKED_F32  # noqa: F401
from models.exported_omnivoice.shaders.silu_f32 import SILU_F32  # noqa: F401
from models.exported_omnivoice.shaders.slice_f32 import SLICE_F32  # noqa: F401
from models.exported_omnivoice.shaders.slice_f32_25 import SLICE_F32_25  # noqa: F401
from models.exported_omnivoice.shaders.slice_f32_30 import SLICE_F32_30  # noqa: F401
from models.exported_omnivoice.shaders.slice_f32_31 import SLICE_F32_31  # noqa: F401
from models.exported_omnivoice.shaders.transpose_f32_45de1e4f84 import TRANSPOSE_F32_45DE1E4F84  # noqa: F401
from models.exported_omnivoice.shaders.transpose_f32_c943282b28 import TRANSPOSE_F32_C943282B28  # noqa: F401
from models.exported_omnivoice.shaders.transpose_f32_f3e8fdf2d4 import TRANSPOSE_F32_F3E8FDF2D4  # noqa: F401
