# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice audio codec tensor scaffold."""

from __future__ import annotations

from dataclasses import dataclass

from torch2vk.runtime.logical import (
    LogicalTensor,
    MemoryClass,
    TensorLifetime,
    TensorRole,
    TensorSemantic,
)
from torch2vk.vulkan.types import TensorSpec

from models.omnivoice.tensors.audio_codec_layer import OmniVoiceAudioCodecDecoderLayerTensors
from models.omnivoice.tensors.audio_codec_layer import declare_omnivoice_audio_codec_decoder_layer_tensors


AUDIO_CODEC_PARAMETER_FIELDS = {
    "quantizer_embed0": "quantizer.quantizers.0.codebook.embed",
    "quantizer_embed1": "quantizer.quantizers.1.codebook.embed",
    "quantizer_embed2": "quantizer.quantizers.2.codebook.embed",
    "quantizer_embed3": "quantizer.quantizers.3.codebook.embed",
    "quantizer_embed4": "quantizer.quantizers.4.codebook.embed",
    "quantizer_embed5": "quantizer.quantizers.5.codebook.embed",
    "quantizer_embed6": "quantizer.quantizers.6.codebook.embed",
    "quantizer_embed7": "quantizer.quantizers.7.codebook.embed",
}


@dataclass(frozen=True, slots=True)
class OmniVoiceAudioCodecTensors:
    audio_tokens: LogicalTensor
    quantizer_embed0: LogicalTensor
    quantizer_embed1: LogicalTensor
    quantizer_embed2: LogicalTensor
    quantizer_embed3: LogicalTensor
    quantizer_embed4: LogicalTensor
    quantizer_embed5: LogicalTensor
    quantizer_embed6: LogicalTensor
    quantizer_embed7: LogicalTensor
    decoder_input: LogicalTensor
    decoder_layers: tuple[OmniVoiceAudioCodecDecoderLayerTensors, ...]
    decoder_hidden: LogicalTensor
    projected_waveform: LogicalTensor
    audio_waveform: LogicalTensor


def declare_omnivoice_audio_codec_tensors(
    *,
    audio_token_length: int,
    audio_sample_length: int,
    num_audio_codebook: int = 8,
) -> OmniVoiceAudioCodecTensors:
    channels = 64
    decoder_layers = tuple(
        declare_omnivoice_audio_codec_decoder_layer_tensors(
            layer=layer,
            channel_count=channels,
            sequence_length=audio_token_length,
        )
        for layer in range(5)
    )
    return OmniVoiceAudioCodecTensors(
        audio_tokens=LogicalTensor(
            name="omnivoice.audio_codec.audio_tokens",
            spec=TensorSpec(dtype="int32", shape=(1, num_audio_codebook, audio_token_length)),
            role=TensorRole.INPUT,
            memory=MemoryClass.HOST_INPUT,
            lifetime=TensorLifetime.FRAME,
            semantic=TensorSemantic.TOKEN,
        ),
        quantizer_embed0=_quantizer_embed("quantizer.quantizers.0.codebook.embed", channels),
        quantizer_embed1=_quantizer_embed("quantizer.quantizers.1.codebook.embed", channels),
        quantizer_embed2=_quantizer_embed("quantizer.quantizers.2.codebook.embed", channels),
        quantizer_embed3=_quantizer_embed("quantizer.quantizers.3.codebook.embed", channels),
        quantizer_embed4=_quantizer_embed("quantizer.quantizers.4.codebook.embed", channels),
        quantizer_embed5=_quantizer_embed("quantizer.quantizers.5.codebook.embed", channels),
        quantizer_embed6=_quantizer_embed("quantizer.quantizers.6.codebook.embed", channels),
        quantizer_embed7=_quantizer_embed("quantizer.quantizers.7.codebook.embed", channels),
        decoder_input=LogicalTensor(
            name="omnivoice.audio_codec.decoder_input",
            spec=TensorSpec(dtype="float32", shape=(1, channels, audio_token_length)),
            role=TensorRole.ACTIVATION,
            memory=MemoryClass.FRAME_WORKSPACE,
            lifetime=TensorLifetime.FRAME,
        ),
        decoder_layers=decoder_layers,
        decoder_hidden=LogicalTensor(
            name="omnivoice.audio_codec.decoder_hidden",
            spec=TensorSpec(dtype="float32", shape=(1, channels, audio_token_length)),
            role=TensorRole.ACTIVATION,
            memory=MemoryClass.FRAME_WORKSPACE,
            lifetime=TensorLifetime.FRAME,
        ),
        projected_waveform=LogicalTensor(
            name="omnivoice.audio_codec.projected_waveform",
            spec=TensorSpec(dtype="float32", shape=(1, audio_sample_length)),
            role=TensorRole.ACTIVATION,
            memory=MemoryClass.FRAME_WORKSPACE,
            lifetime=TensorLifetime.FRAME,
        ),
        audio_waveform=LogicalTensor(
            name="omnivoice.audio_codec.audio_waveform",
            spec=TensorSpec(dtype="float32", shape=(1, audio_sample_length)),
            role=TensorRole.OUTPUT,
            memory=MemoryClass.HOST_OUTPUT,
            lifetime=TensorLifetime.FRAME,
            semantic=TensorSemantic.WAVEFORM,
        ),
    )


def _quantizer_embed(name: str, channels: int) -> LogicalTensor:
    return LogicalTensor(
        name=name,
        spec=TensorSpec(dtype="float32", shape=(1024, channels)),
        role=TensorRole.WEIGHT,
        memory=MemoryClass.MODEL_WEIGHT,
        lifetime=TensorLifetime.MODEL,
        checkpoint="audio_tokenizer/model.safetensors",
    )
