# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice audio codec decoder layer tensor scaffold."""

from __future__ import annotations

from dataclasses import dataclass

from torch2vk.runtime.logical import LogicalTensor


AUDIO_CODEC_DECODER_LAYER_PARAMETER_FIELDS = {}


@dataclass(frozen=True, slots=True)
class OmniVoiceAudioCodecDecoderLayerTensors:
    conv1_weight: LogicalTensor
    conv1_bias: LogicalTensor
    conv7_weight: LogicalTensor
    conv7_bias: LogicalTensor
    deconv_weight: LogicalTensor
    deconv_bias: LogicalTensor
    decoder_hidden: LogicalTensor
    snake_activation: LogicalTensor
    decoder_residual: LogicalTensor
    output: LogicalTensor


def declare_omnivoice_audio_codec_decoder_layer_tensors(
    *,
    layer: int,
    channel_count: int,
    sequence_length: int,
) -> OmniVoiceAudioCodecDecoderLayerTensors:
    raise NotImplementedError(
        "Generated scaffold only: fill one OmniVoice audio codec decoder layer declaration."
    )
