# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice audio codec tensor scaffold."""

from __future__ import annotations

from dataclasses import dataclass

from torch2vk.runtime.logical import LogicalTensor, TensorSemantic

from models.omnivoice.tensors._logical import (
    activation_tensor as _activation,
    host_output_tensor as _host_output,
    input_tensor as _input,
    weight_tensor as _weight,
)
from models.omnivoice.tensors.audio_codec_layer import OmniVoiceAudioCodecDecoderLayerTensors
from models.omnivoice.tensors.audio_codec_layer import declare_omnivoice_audio_codec_decoder_layer_tensors


AUDIO_CODEC_PARAMETER_FIELDS = {
    'quantizer_embed0': 'quantizer.quantizers.0.codebook.embed',
    'quantizer_embed1': 'quantizer.quantizers.1.codebook.embed',
    'quantizer_embed2': 'quantizer.quantizers.2.codebook.embed',
    'quantizer_embed3': 'quantizer.quantizers.3.codebook.embed',
    'quantizer_embed4': 'quantizer.quantizers.4.codebook.embed',
    'quantizer_embed5': 'quantizer.quantizers.5.codebook.embed',
    'quantizer_embed6': 'quantizer.quantizers.6.codebook.embed',
    'quantizer_embed7': 'quantizer.quantizers.7.codebook.embed',
}


@dataclass(frozen=True, slots=True)
class OmniVoiceAudioCodecTensors:
    audio_tokens: LogicalTensor
    quantizer_embed0: LogicalTensor
    quantizer_embed1: LogicalTensor
    quantizer_embed2: LogicalTensor
    quantizer_embed3: LogicalTensor
    quantizer_embed4: LogicalTensor
    quantizer_embed5: LogicalTensor
    quantizer_embed6: LogicalTensor
    quantizer_embed7: LogicalTensor
    decoder_input: LogicalTensor
    decoder_layers: tuple[OmniVoiceAudioCodecDecoderLayerTensors, ...]
    decoder_hidden: LogicalTensor
    projected_waveform: LogicalTensor
    audio_waveform: LogicalTensor


def declare_omnivoice_audio_codec_tensors(
    *,
    audio_token_length: int,
    audio_sample_length: int,
    num_audio_codebook: int = 8,
) -> OmniVoiceAudioCodecTensors:
    channels = 64
    decoder_layers = tuple(
        declare_omnivoice_audio_codec_decoder_layer_tensors(
            layer=layer,
            channel_count=channels,
            sequence_length=audio_token_length,
        )
        for layer in range(5)
    )
    return OmniVoiceAudioCodecTensors(
        audio_tokens=_input(
            "omnivoice.audio_codec.audio_tokens",
            "int32",
            (1, num_audio_codebook, audio_token_length),
        ),
        quantizer_embed0=_quantizer_embed("quantizer.quantizers.0.codebook.embed", channels),
        quantizer_embed1=_quantizer_embed("quantizer.quantizers.1.codebook.embed", channels),
        quantizer_embed2=_quantizer_embed("quantizer.quantizers.2.codebook.embed", channels),
        quantizer_embed3=_quantizer_embed("quantizer.quantizers.3.codebook.embed", channels),
        quantizer_embed4=_quantizer_embed("quantizer.quantizers.4.codebook.embed", channels),
        quantizer_embed5=_quantizer_embed("quantizer.quantizers.5.codebook.embed", channels),
        quantizer_embed6=_quantizer_embed("quantizer.quantizers.6.codebook.embed", channels),
        quantizer_embed7=_quantizer_embed("quantizer.quantizers.7.codebook.embed", channels),
        decoder_input=_activation(
            "omnivoice.audio_codec.decoder_input",
            (1, channels, audio_token_length),
        ),
        decoder_layers=decoder_layers,
        decoder_hidden=_activation(
            "omnivoice.audio_codec.decoder_hidden",
            (1, channels, audio_token_length),
        ),
        projected_waveform=_activation(
            "omnivoice.audio_codec.projected_waveform",
            (1, audio_sample_length),
        ),
        audio_waveform=_host_output(
            "omnivoice.audio_codec.audio_waveform",
            "float32",
            (1, audio_sample_length),
            semantic=TensorSemantic.WAVEFORM,
        ),
    )


def _quantizer_embed(name: str, channels: int) -> LogicalTensor:
    return _weight(
        name,
        (1024, channels),
        dtype="float32",
        checkpoint="audio_tokenizer/model.safetensors",
    )
