# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice inference orchestration tensor scaffold."""

from __future__ import annotations

from dataclasses import dataclass

from torch2vk.runtime.logical import LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceReferencePromptTensors:
    ref_audio: LogicalTensor
    ref_waveform: LogicalTensor
    trimmed_ref_waveform: LogicalTensor
    ref_chunk_size: LogicalTensor
    ref_audio_tokens: LogicalTensor
    ref_text_tokens: LogicalTensor
    ref_rms: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoicePreparedInputTensors:
    style_tokens: LogicalTensor
    text_tokens: LogicalTensor
    ref_audio_tokens: LogicalTensor | None
    target_audio_tokens: LogicalTensor
    cond_input_ids: LogicalTensor
    cond_audio_mask: LogicalTensor
    cond_total_length: LogicalTensor
    cond_audio_start_idx: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceIterativeDecodeTensors:
    reference_prompt: OmniVoiceReferencePromptTensors | None
    prepared_inputs: tuple[OmniVoicePreparedInputTensors, ...]
    c_lens: LogicalTensor
    u_lens: LogicalTensor
    target_lens: LogicalTensor
    batch_input_ids: LogicalTensor
    batch_audio_mask: LogicalTensor
    batch_attention_mask: LogicalTensor
    tokens: LogicalTensor
    timesteps: LogicalTensor
    schedules: LogicalTensor
    layer_ids: LogicalTensor
    batch_logits: LogicalTensor
    cond_logits: LogicalTensor
    uncond_logits: LogicalTensor
    sample_tokens: LogicalTensor
    topk_values: LogicalTensor
    topk_indices: LogicalTensor
    flat_tokens: LogicalTensor
    updated_sample_tokens: LogicalTensor
    updated_batch_input_ids: LogicalTensor


def declare_omnivoice_iterative_decode_tensors(
    *,
    batch_size: int,
    max_condition_length: int,
    max_target_tokens: int,
    num_step: int,
    audio_vocab_size: int = 1025,
    num_audio_codebook: int = 8,
) -> OmniVoiceIterativeDecodeTensors:
    raise NotImplementedError(
        "Generated scaffold only: fill OmniVoice iterative generation tensor declarations."
    )
