# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice text frame tensor scaffold."""

from __future__ import annotations

from dataclasses import dataclass

from torch2vk.runtime.logical import (
    ComparePolicy,
    LogicalTensor,
    MemoryClass,
    PyTorchProbe,
    TensorLifetime,
    TensorRole,
    TensorSemantic,
    TensorSpec,
)

from models.omnivoice.tensors.text_layer import OmniVoiceTextLayerTensors


TEXT_PARAMETER_FIELDS = {
    "embed_tokens_weight": "llm.embed_tokens.weight",
    "audio_embeddings_weight": "audio_embeddings.weight",
    "codebook_layer_offsets": "codebook_layer_offsets",
    "norm_weight": "llm.norm.weight",
    "audio_heads_weight": "audio_heads.weight",
}


@dataclass(frozen=True, slots=True)
class OmniVoiceTextPrefillTensors:
    input_ids: LogicalTensor
    audio_mask: LogicalTensor
    attention_mask: LogicalTensor
    position_ids: LogicalTensor
    embed_tokens_weight: LogicalTensor
    audio_embeddings_weight: LogicalTensor
    codebook_layer_offsets: LogicalTensor
    text_token_ids: LogicalTensor
    text_embeds: LogicalTensor
    audio_mask_for_shift: LogicalTensor
    masked_audio_ids: LogicalTensor
    codebook_layer_offsets_view: LogicalTensor
    shifted_ids: LogicalTensor
    audio_embedding_values: LogicalTensor
    audio_embeds: LogicalTensor
    audio_mask_expanded: LogicalTensor
    inputs_embeds: LogicalTensor
    layers: tuple[OmniVoiceTextLayerTensors, ...]
    norm_weight: LogicalTensor
    llm_hidden_states: LogicalTensor
    final_norm: LogicalTensor
    hidden_states: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceTextDecodeTensors:
    input_ids: LogicalTensor
    audio_mask: LogicalTensor
    attention_mask: LogicalTensor
    position_ids: LogicalTensor
    cache_position: LogicalTensor
    embed_tokens_weight: LogicalTensor
    audio_embeddings_weight: LogicalTensor
    codebook_layer_offsets: LogicalTensor
    text_token_ids: LogicalTensor
    text_embeds: LogicalTensor
    audio_mask_for_shift: LogicalTensor
    masked_audio_ids: LogicalTensor
    codebook_layer_offsets_view: LogicalTensor
    shifted_ids: LogicalTensor
    audio_embedding_values: LogicalTensor
    audio_embeds: LogicalTensor
    audio_mask_expanded: LogicalTensor
    inputs_embeds: LogicalTensor
    layers: tuple[OmniVoiceTextLayerTensors, ...]
    norm_weight: LogicalTensor
    llm_hidden_states: LogicalTensor
    final_norm: LogicalTensor
    hidden_states: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceAudioHeadTensors:
    hidden_states: LogicalTensor
    audio_heads_weight: LogicalTensor
    logits_flat: LogicalTensor
    audio_logits_view: LogicalTensor
    audio_logits: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceTokenSelectTensors:
    cond_logits: LogicalTensor
    uncond_logits: LogicalTensor
    c_log_probs: LogicalTensor
    u_log_probs: LogicalTensor
    guided_logits: LogicalTensor
    log_probs: LogicalTensor
    masked_log_probs: LogicalTensor
    filtered_probs: LogicalTensor
    class_gumbel_uniform: LogicalTensor
    class_gumbel_noise: LogicalTensor
    class_sample_logits: LogicalTensor
    pred_tokens: LogicalTensor
    confidence_scores: LogicalTensor
    layer_ids: LogicalTensor
    position_scores: LogicalTensor
    position_gumbel_uniform: LogicalTensor
    position_gumbel_noise: LogicalTensor
    current_tokens: LogicalTensor
    topk_values: LogicalTensor
    topk_indices: LogicalTensor
    selected_positions: LogicalTensor
    updated_tokens: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceTrainingLossTensors:
    labels: LogicalTensor
    logits_for_loss: LogicalTensor
    per_token_loss: LogicalTensor
    valid_mask: LogicalTensor
    layer_loss_sum: LogicalTensor
    layer_valid_count: LogicalTensor
    layer_means: LogicalTensor
    loss_weights: LogicalTensor
    loss: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceTextTensors:
    prefill: OmniVoiceTextPrefillTensors
    decode: OmniVoiceTextDecodeTensors
    audio_head: OmniVoiceAudioHeadTensors
    token_select: OmniVoiceTokenSelectTensors
    training_loss: OmniVoiceTrainingLossTensors | None


def declare_omnivoice_text_tensors(
    *,
    batch_size: int,
    prompt_length: int,
    max_sequence_length: int,
    hidden_size: int = 1024,
    intermediate_size: int = 3072,
    vocab_size: int = 151676,
    decoder_layers: int = 28,
    num_attention_heads: int = 16,
    num_key_value_heads: int = 8,
    head_dim: int = 128,
    audio_vocab_size: int = 1025,
    num_audio_codebook: int = 8,
) -> OmniVoiceTextTensors:
    prefill = _declare_omnivoice_text_prefill_tensors(
        prefix="omnivoice.prefill",
        batch_size=batch_size,
        sequence_length=prompt_length,
        hidden_size=hidden_size,
        vocab_size=vocab_size,
        audio_vocab_size=audio_vocab_size,
        num_audio_codebook=num_audio_codebook,
    )
    decode = _declare_omnivoice_text_decode_tensors(
        prefix="omnivoice.decode",
        batch_size=batch_size,
        sequence_length=1,
        max_sequence_length=max_sequence_length,
        hidden_size=hidden_size,
        vocab_size=vocab_size,
        audio_vocab_size=audio_vocab_size,
        num_audio_codebook=num_audio_codebook,
    )
    audio_head = OmniVoiceAudioHeadTensors(
        hidden_states=_activation(
            "omnivoice.audio_head.hidden_states",
            "float32",
            (batch_size, max_sequence_length, hidden_size),
        ),
        audio_heads_weight=_weight(
            "audio_heads.weight",
            "float32",
            (num_audio_codebook * audio_vocab_size, hidden_size),
        ),
        logits_flat=_activation(
            "omnivoice.audio_head.logits_flat",
            "float32",
            (batch_size, max_sequence_length, num_audio_codebook * audio_vocab_size),
        ),
        audio_logits_view=_activation(
            "omnivoice.audio_head.audio_logits_view",
            "float32",
            (batch_size, max_sequence_length, num_audio_codebook, audio_vocab_size),
        ),
        audio_logits=LogicalTensor(
            name="omnivoice.audio_head.audio_logits",
            spec=TensorSpec(
                dtype="float32",
                shape=(batch_size, num_audio_codebook, max_sequence_length, audio_vocab_size),
            ),
            role=TensorRole.OUTPUT,
            memory=MemoryClass.HOST_OUTPUT,
            lifetime=TensorLifetime.FRAME,
            semantic=TensorSemantic.LOGITS,
        ),
    )
    return OmniVoiceTextTensors(
        prefill=prefill,
        decode=decode,
        audio_head=audio_head,
        token_select=_declare_omnivoice_token_select_tensors(
            batch_size=batch_size,
            sequence_length=max_sequence_length,
            audio_vocab_size=audio_vocab_size,
            num_audio_codebook=num_audio_codebook,
        ),
        training_loss=None,
    )


def _declare_omnivoice_text_prefill_tensors(
    *,
    prefix: str,
    batch_size: int,
    sequence_length: int,
    hidden_size: int,
    vocab_size: int,
    audio_vocab_size: int,
    num_audio_codebook: int,
) -> OmniVoiceTextPrefillTensors:
    common = _common_text_tensors(
        prefix=prefix,
        batch_size=batch_size,
        sequence_length=sequence_length,
        hidden_size=hidden_size,
        vocab_size=vocab_size,
        audio_vocab_size=audio_vocab_size,
        num_audio_codebook=num_audio_codebook,
    )
    return OmniVoiceTextPrefillTensors(**common)


def _declare_omnivoice_text_decode_tensors(
    *,
    prefix: str,
    batch_size: int,
    sequence_length: int,
    max_sequence_length: int,
    hidden_size: int,
    vocab_size: int,
    audio_vocab_size: int,
    num_audio_codebook: int,
) -> OmniVoiceTextDecodeTensors:
    common = _common_text_tensors(
        prefix=prefix,
        batch_size=batch_size,
        sequence_length=sequence_length,
        hidden_size=hidden_size,
        vocab_size=vocab_size,
        audio_vocab_size=audio_vocab_size,
        num_audio_codebook=num_audio_codebook,
    )
    return OmniVoiceTextDecodeTensors(
        **common,
        cache_position=_input(f"{prefix}.cache_position", "int64", (1,)),
    )


def _common_text_tensors(
    *,
    prefix: str,
    batch_size: int,
    sequence_length: int,
    hidden_size: int,
    vocab_size: int,
    audio_vocab_size: int,
    num_audio_codebook: int,
) -> dict[str, object]:
    hidden_shape = (batch_size, sequence_length, hidden_size)
    return {
        "input_ids": _input(
            f"{prefix}.input_ids",
            "int64",
            (batch_size, num_audio_codebook, sequence_length),
        ),
        "audio_mask": _input(f"{prefix}.audio_mask", "bool", (batch_size, sequence_length)),
        "attention_mask": _input(
            f"{prefix}.attention_mask", "uint32", (batch_size, sequence_length)
        ),
        "position_ids": _input(f"{prefix}.position_ids", "int64", (batch_size, sequence_length)),
        "embed_tokens_weight": _weight(
            "llm.embed_tokens.weight", "float32", (vocab_size, hidden_size)
        ),
        "audio_embeddings_weight": _weight(
            "audio_embeddings.weight",
            "float32",
            (num_audio_codebook * audio_vocab_size, hidden_size),
        ),
        "codebook_layer_offsets": _weight(
            "codebook_layer_offsets", "int64", (num_audio_codebook,)
        ),
        "text_token_ids": LogicalTensor(
            name=f"{prefix}.text_token_ids",
            spec=TensorSpec(dtype="int64", shape=(batch_size, sequence_length)),
            role=TensorRole.OUTPUT,
            memory=MemoryClass.HOST_OUTPUT,
            lifetime=TensorLifetime.FRAME,
            semantic=TensorSemantic.TOKEN,
            compare=ComparePolicy(kind="token"),
            pytorch_probe=PyTorchProbe(kind="module_input", target="llm.embed_tokens"),
        ),
        "text_embeds": LogicalTensor(
            name=f"{prefix}.text_embeds",
            spec=TensorSpec(dtype="float32", shape=hidden_shape),
            role=TensorRole.OUTPUT,
            memory=MemoryClass.HOST_OUTPUT,
            lifetime=TensorLifetime.FRAME,
            compare=ComparePolicy(kind="tensor", rtol=1e-4, atol=1e-4),
            pytorch_probe=PyTorchProbe(kind="module_output", target="llm.embed_tokens"),
        ),
        "audio_mask_for_shift": _activation(
            f"{prefix}.audio_mask_for_shift", "bool", (batch_size, 1, sequence_length)
        ),
        "masked_audio_ids": _activation(
            f"{prefix}.masked_audio_ids",
            "int64",
            (batch_size, num_audio_codebook, sequence_length),
        ),
        "codebook_layer_offsets_view": _activation(
            f"{prefix}.codebook_layer_offsets_view", "int64", (1, num_audio_codebook, 1)
        ),
        "shifted_ids": _activation(
            f"{prefix}.shifted_ids",
            "int64",
            (batch_size, num_audio_codebook, sequence_length),
        ),
        "audio_embedding_values": _activation(
            f"{prefix}.audio_embedding_values",
            "float32",
            (batch_size, num_audio_codebook, sequence_length, hidden_size),
        ),
        "audio_embeds": LogicalTensor(
            name=f"{prefix}.audio_embeds",
            spec=TensorSpec(dtype="float32", shape=hidden_shape),
            role=TensorRole.OUTPUT,
            memory=MemoryClass.HOST_OUTPUT,
            lifetime=TensorLifetime.FRAME,
            compare=ComparePolicy(kind="tensor", rtol=1e-4, atol=1e-4),
        ),
        "audio_mask_expanded": _activation(
            f"{prefix}.audio_mask_expanded", "bool", (batch_size, sequence_length, 1)
        ),
        "inputs_embeds": _activation(f"{prefix}.inputs_embeds", "float32", hidden_shape),
        "layers": (),
        "norm_weight": _weight("llm.norm.weight", "float32", (hidden_size,)),
        "llm_hidden_states": _activation(f"{prefix}.llm_hidden_states", "float32", hidden_shape),
        "final_norm": _activation(f"{prefix}.final_norm", "float32", hidden_shape),
        "hidden_states": _activation(f"{prefix}.hidden_states", "float32", hidden_shape),
    }


def _declare_omnivoice_token_select_tensors(
    *,
    batch_size: int,
    sequence_length: int,
    audio_vocab_size: int,
    num_audio_codebook: int,
) -> OmniVoiceTokenSelectTensors:
    logits_shape = (batch_size, num_audio_codebook, sequence_length, audio_vocab_size)
    token_shape = (batch_size, num_audio_codebook, sequence_length)
    score_shape = (batch_size, num_audio_codebook, sequence_length)
    position_shape = (batch_size, num_audio_codebook)
    return OmniVoiceTokenSelectTensors(
        cond_logits=_activation("omnivoice.token_select.cond_logits", "float32", logits_shape),
        uncond_logits=_activation("omnivoice.token_select.uncond_logits", "float32", logits_shape),
        c_log_probs=_activation("omnivoice.token_select.c_log_probs", "float32", logits_shape),
        u_log_probs=_activation("omnivoice.token_select.u_log_probs", "float32", logits_shape),
        guided_logits=_input("omnivoice.token_select.guided_logits", "float32", logits_shape),
        log_probs=_activation("omnivoice.token_select.log_probs", "float32", logits_shape),
        masked_log_probs=_activation(
            "omnivoice.token_select.masked_log_probs", "float32", logits_shape
        ),
        filtered_probs=_activation("omnivoice.token_select.filtered_probs", "float32", logits_shape),
        class_gumbel_uniform=_input(
            "omnivoice.token_select.class_gumbel_uniform", "float32", logits_shape
        ),
        class_gumbel_noise=_activation(
            "omnivoice.token_select.class_gumbel_noise", "float32", logits_shape
        ),
        class_sample_logits=_activation(
            "omnivoice.token_select.class_sample_logits", "float32", logits_shape
        ),
        pred_tokens=_activation("omnivoice.token_select.pred_tokens", "int32", token_shape),
        confidence_scores=_activation(
            "omnivoice.token_select.confidence_scores", "float32", score_shape
        ),
        layer_ids=_input("omnivoice.token_select.layer_ids", "int32", (num_audio_codebook,)),
        position_scores=_input("omnivoice.token_select.position_scores", "float32", position_shape),
        position_gumbel_uniform=_input(
            "omnivoice.token_select.position_gumbel_uniform", "float32", position_shape
        ),
        position_gumbel_noise=_activation(
            "omnivoice.token_select.position_gumbel_noise", "float32", position_shape
        ),
        current_tokens=_input("omnivoice.token_select.current_tokens", "int32", token_shape),
        topk_values=_activation(
            "omnivoice.token_select.topk_values", "float32", (batch_size, num_audio_codebook)
        ),
        topk_indices=_activation(
            "omnivoice.token_select.topk_indices", "int32", (batch_size, num_audio_codebook)
        ),
        selected_positions=_activation(
            "omnivoice.token_select.selected_positions", "int32", (batch_size, num_audio_codebook)
        ),
        updated_tokens=LogicalTensor(
            name="omnivoice.token_select.updated_tokens",
            spec=TensorSpec(dtype="int32", shape=token_shape),
            role=TensorRole.OUTPUT,
            memory=MemoryClass.HOST_OUTPUT,
            lifetime=TensorLifetime.FRAME,
            semantic=TensorSemantic.TOKEN,
        ),
    )


def _weight(name: str, dtype: str, shape: tuple[int, ...]) -> LogicalTensor:
    return LogicalTensor(
        name=name,
        spec=TensorSpec(dtype=dtype, shape=shape),
        role=TensorRole.WEIGHT,
        memory=MemoryClass.MODEL_WEIGHT,
        lifetime=TensorLifetime.MODEL,
    )


def _input(name: str, dtype: str, shape: tuple[int, ...]) -> LogicalTensor:
    return LogicalTensor(
        name=name,
        spec=TensorSpec(dtype=dtype, shape=shape),
        role=TensorRole.INPUT,
        memory=MemoryClass.HOST_INPUT,
        lifetime=TensorLifetime.FRAME,
    )


def _activation(name: str, dtype: str, shape: tuple[int, ...]) -> LogicalTensor:
    return LogicalTensor(
        name=name,
        spec=TensorSpec(dtype=dtype, shape=shape),
        role=TensorRole.ACTIVATION,
        memory=MemoryClass.FRAME_WORKSPACE,
        lifetime=TensorLifetime.FRAME,
    )
