# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice text frame tensor scaffold."""

from __future__ import annotations

from dataclasses import dataclass

from torch2vk.runtime.logical import LogicalTensor

from models.omnivoice.tensors.text_layer import OmniVoiceTextLayerTensors


TEXT_PARAMETER_FIELDS = {
    "embed_tokens_weight": "llm.embed_tokens.weight",
    "audio_embeddings_weight": "audio_embeddings.weight",
    "codebook_layer_offsets": "codebook_layer_offsets",
    "norm_weight": "llm.norm.weight",
    "audio_heads_weight": "audio_heads.weight",
}


@dataclass(frozen=True, slots=True)
class OmniVoiceTextPrefillTensors:
    input_ids: LogicalTensor
    audio_mask: LogicalTensor
    attention_mask: LogicalTensor
    position_ids: LogicalTensor
    embed_tokens_weight: LogicalTensor
    audio_embeddings_weight: LogicalTensor
    codebook_layer_offsets: LogicalTensor
    text_embeds: LogicalTensor
    shifted_ids: LogicalTensor
    audio_embeds: LogicalTensor
    audio_mask_expanded: LogicalTensor
    inputs_embeds: LogicalTensor
    layers: tuple[OmniVoiceTextLayerTensors, ...]
    norm_weight: LogicalTensor
    llm_hidden_states: LogicalTensor
    final_norm: LogicalTensor
    hidden_states: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceTextDecodeTensors:
    input_ids: LogicalTensor
    audio_mask: LogicalTensor
    attention_mask: LogicalTensor
    position_ids: LogicalTensor
    cache_position: LogicalTensor
    embed_tokens_weight: LogicalTensor
    audio_embeddings_weight: LogicalTensor
    codebook_layer_offsets: LogicalTensor
    text_embeds: LogicalTensor
    shifted_ids: LogicalTensor
    audio_embeds: LogicalTensor
    audio_mask_expanded: LogicalTensor
    inputs_embeds: LogicalTensor
    layers: tuple[OmniVoiceTextLayerTensors, ...]
    norm_weight: LogicalTensor
    llm_hidden_states: LogicalTensor
    final_norm: LogicalTensor
    hidden_states: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceAudioHeadTensors:
    hidden_states: LogicalTensor
    audio_heads_weight: LogicalTensor
    logits_flat: LogicalTensor
    audio_logits_view: LogicalTensor
    audio_logits: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceTokenSelectTensors:
    cond_logits: LogicalTensor
    uncond_logits: LogicalTensor
    c_log_probs: LogicalTensor
    u_log_probs: LogicalTensor
    guided_logits: LogicalTensor
    log_probs: LogicalTensor
    masked_log_probs: LogicalTensor
    filtered_probs: LogicalTensor
    class_gumbel_uniform: LogicalTensor
    class_gumbel_noise: LogicalTensor
    class_sample_logits: LogicalTensor
    pred_tokens: LogicalTensor
    confidence_scores: LogicalTensor
    layer_ids: LogicalTensor
    position_scores: LogicalTensor
    position_gumbel_uniform: LogicalTensor
    position_gumbel_noise: LogicalTensor
    current_tokens: LogicalTensor
    topk_values: LogicalTensor
    topk_indices: LogicalTensor
    selected_positions: LogicalTensor
    updated_tokens: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceTrainingLossTensors:
    labels: LogicalTensor
    logits_for_loss: LogicalTensor
    per_token_loss: LogicalTensor
    valid_mask: LogicalTensor
    layer_loss_sum: LogicalTensor
    layer_valid_count: LogicalTensor
    layer_means: LogicalTensor
    loss_weights: LogicalTensor
    loss: LogicalTensor


@dataclass(frozen=True, slots=True)
class OmniVoiceTextTensors:
    prefill: OmniVoiceTextPrefillTensors
    decode: OmniVoiceTextDecodeTensors
    audio_head: OmniVoiceAudioHeadTensors
    token_select: OmniVoiceTokenSelectTensors
    training_loss: OmniVoiceTrainingLossTensors | None


def declare_omnivoice_text_tensors(
    *,
    batch_size: int,
    prompt_length: int,
    max_sequence_length: int,
    hidden_size: int = 1024,
    intermediate_size: int = 3072,
    vocab_size: int = 151676,
    decoder_layers: int = 28,
    num_attention_heads: int = 16,
    num_key_value_heads: int = 8,
    head_dim: int = 128,
    audio_vocab_size: int = 1025,
    num_audio_codebook: int = 8,
) -> OmniVoiceTextTensors:
    raise NotImplementedError(
        "Generated scaffold only: fill OmniVoice text/audio-head tensor declarations."
    )
