# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice text decoder layer tensor scaffold."""

from __future__ import annotations

from dataclasses import dataclass

from torch2vk.runtime.logical import LogicalTensor


TEXT_DECODER_LAYER_PARAMETER_FIELDS = {
    "input_layernorm_weight": "input_layernorm.weight",
    "post_attention_layernorm_weight": "post_attention_layernorm.weight",
    "q_norm_weight": "self_attn.q_norm.weight",
    "k_norm_weight": "self_attn.k_norm.weight",
    "q_proj_weight": "self_attn.q_proj.weight",
    "k_proj_weight": "self_attn.k_proj.weight",
    "v_proj_weight": "self_attn.v_proj.weight",
    "o_proj_weight": "self_attn.o_proj.weight",
    "gate_proj_weight": "mlp.gate_proj.weight",
    "up_proj_weight": "mlp.up_proj.weight",
    "down_proj_weight": "mlp.down_proj.weight",
}


@dataclass(frozen=True, slots=True)
class OmniVoiceTextLayerTensors:
    input_layernorm_weight: LogicalTensor
    post_attention_layernorm_weight: LogicalTensor
    q_norm_weight: LogicalTensor
    k_norm_weight: LogicalTensor
    q_proj_weight: LogicalTensor
    k_proj_weight: LogicalTensor
    v_proj_weight: LogicalTensor
    o_proj_weight: LogicalTensor
    gate_proj_weight: LogicalTensor
    up_proj_weight: LogicalTensor
    down_proj_weight: LogicalTensor
    input_layernorm: LogicalTensor
    q_proj: LogicalTensor
    k_proj: LogicalTensor
    v_proj: LogicalTensor
    q_normed: LogicalTensor
    k_normed: LogicalTensor
    q_roped: LogicalTensor
    k_roped: LogicalTensor
    key_cache: LogicalTensor
    value_cache: LogicalTensor
    attention: LogicalTensor
    o_proj: LogicalTensor
    attn_residual: LogicalTensor
    post_attention_layernorm: LogicalTensor
    gate_proj: LogicalTensor
    up_proj: LogicalTensor
    swiglu: LogicalTensor
    down_proj: LogicalTensor
    output: LogicalTensor


def declare_omnivoice_text_layer_tensors(
    *,
    frame_prefix: str,
    layer: int,
    sequence_length: int,
    max_sequence_length: int,
    hidden_size: int,
    intermediate_size: int,
    num_attention_heads: int,
    num_key_value_heads: int,
    head_dim: int,
    key_cache: LogicalTensor | None = None,
    value_cache: LogicalTensor | None = None,
) -> OmniVoiceTextLayerTensors:
    raise NotImplementedError(
        "Generated scaffold only: fill one OmniVoice text decoder layer tensor declaration."
    )
