# This file is generated by torch2vk.export. Do not edit by hand.
"""Qwen3-ASR encoder self-attention shader.

The imported baseline uses cooperative matrices for the large-QKV path. This
variant keeps Q/K/V projection in the tiled linear shader and computes four
query rows per head/workgroup. The kernel uses flash-attention style online
softmax, so K/V are streamed once per query block instead of writing logits and
reading V in a second pass.
"""

from __future__ import annotations

from torch2vk.runtime.shader import (
    IOKind,
    PushConstantFieldSpec,
    PushConstantSpec,
    PushConstantType,
    ShaderContract,
    ShaderVariant,
    TensorContract,
    TensorFieldSpec,
    ceil_div,
)
from torch2vk.vulkan.shader_execution_requirements import (
    ShaderExecutionRequirements,
    SubgroupRequirements,
)


ENCODER_ATTENTION_F32 = ShaderVariant(
    name="encoder_attention_f32",
    family="qwen3_asr.audio_tower",
    contract=ShaderContract(
        class_name="Qwen3AsrEncoderAttentionF32Program",
        shader_name="encoder_attention_f32",
        fields=(
            TensorFieldSpec(
                name="q",
                io_kind=IOKind.INPUT,
                role="input",
                contract=TensorContract(dtype="float32", shape=("M", "H")),
            ),
            TensorFieldSpec(
                name="k",
                io_kind=IOKind.INPUT,
                role="input",
                contract=TensorContract(dtype="float32", shape=("M", "H")),
            ),
            TensorFieldSpec(
                name="v",
                io_kind=IOKind.INPUT,
                role="input",
                contract=TensorContract(dtype="float32", shape=("M", "H")),
            ),
            TensorFieldSpec(
                name="cu_seqlens",
                io_kind=IOKind.INPUT,
                role="input",
                contract=TensorContract(dtype="uint32", shape=("S",)),
            ),
            TensorFieldSpec(
                name="output",
                io_kind=IOKind.OUTPUT,
                role="output",
                contract=TensorContract(dtype="float32", shape=("M", "H")),
            ),
        ),
        push_constants=PushConstantSpec(
            size=20,
            fields=(
                PushConstantFieldSpec("M", PushConstantType.UINT32, 0, "M"),
                PushConstantFieldSpec("H", PushConstantType.UINT32, 4, "H"),
                PushConstantFieldSpec("num_heads", PushConstantType.UINT32, 8, 14),
                PushConstantFieldSpec("head_dim", PushConstantType.UINT32, 12, 64),
                PushConstantFieldSpec("S", PushConstantType.UINT32, 16, "S"),
            ),
        ),
        dispatch=(ceil_div("M", 4), 14, 1),
    ),
    execution_requirements=ShaderExecutionRequirements(
        subgroup=SubgroupRequirements(required_size=64, require_full_subgroups=True)
    ),
    source="""
#version 450

#extension GL_EXT_control_flow_attributes : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_arithmetic : enable

layout(std430) buffer;

layout(set = 0, binding = 0) buffer restrict readonly QBuffer {
    float q_values[];
};

layout(set = 0, binding = 1) buffer restrict readonly KBuffer {
    float k_values[];
};

layout(set = 0, binding = 2) buffer restrict readonly VBuffer {
    float v_values[];
};

layout(set = 0, binding = 3) buffer restrict readonly CuSeqlensBuffer {
    uint cu_seqlens[];
};

layout(set = 0, binding = 4) buffer restrict writeonly OutputBuffer {
    float output_values[];
};

layout(push_constant) uniform PushConstants {
    uint M;
    uint H;
    uint num_heads;
    uint head_dim;
    uint S;
} pc;

layout(local_size_x = 64, local_size_y = 4, local_size_z = 1) in;

const uint QUERY_ROWS = 4u;
const float NEG_INF = -3.4028234663852886e38;

shared float subgroup_dot[4][4];
shared float k_tile[64];
shared float v_tile[64];

void main() {
    const uint query_lane = gl_LocalInvocationID.y;
    const uint row = gl_WorkGroupID.x * QUERY_ROWS + query_lane;
    const uint head = gl_WorkGroupID.y;
    const uint dim = gl_LocalInvocationID.x;
    if (head >= pc.num_heads || dim >= pc.head_dim) {
        return;
    }

    const uint head_offset = head * pc.head_dim;
    const uint q_base = row * pc.H + head_offset;
    const bool valid_query = row < pc.M;
    const float q_value = valid_query ? q_values[q_base + dim] : 0.0;
    const float scale = inversesqrt(float(pc.head_dim));

    float running_max = NEG_INF;
    float running_sum = 0.0;
    float acc = 0.0;
    for (uint key_row = 0u; key_row < pc.M; ++key_row) {
        if (query_lane == 0u) {
            const uint base = key_row * pc.H + head_offset;
            k_tile[dim] = k_values[base + dim];
            v_tile[dim] = v_values[base + dim];
        }
        barrier();

        const float dot_part = q_value * k_tile[dim];
        const float dot_sum = subgroupAdd(dot_part);
        if (gl_SubgroupInvocationID == 0u) {
            subgroup_dot[query_lane][dim / gl_SubgroupSize] = dot_sum;
        }
        barrier();

        if (valid_query) {
            float dot = 0.0;
            for (uint i = 0u; i < (pc.head_dim + gl_SubgroupSize - 1u) / gl_SubgroupSize; ++i) {
                dot += subgroup_dot[query_lane][i];
            }
            const float score = dot * scale;
            const float next_max = max(running_max, score);
            const float old_scale = running_max == NEG_INF ? 0.0 : exp(running_max - next_max);
            const float score_scale = exp(score - next_max);
            acc = acc * old_scale + score_scale * v_tile[dim];
            running_sum = running_sum * old_scale + score_scale;
            running_max = next_max;
        }
        barrier();
    }

    if (valid_query) {
        output_values[row * pc.H + head_offset + dim] = acc / running_sum;
    }
}
""".lstrip(),
)
