# This file is generated by torch2vk.export. Do not edit by hand.
"""Qwen3-ASR rotary position embeddings using precomputed cos/sin."""

from __future__ import annotations

from torch2vk.runtime.shader import (
    IOKind,
    PushConstantFieldSpec,
    PushConstantSpec,
    PushConstantType,
    ShaderContract,
    ShaderVariant,
    TensorContract,
    TensorFieldSpec,
    ceil_div,
    mul,
)


TEXT_ROPE_F32 = ShaderVariant(
    name="text_rope_f32",
    family="qwen3_asr.text",
    contract=ShaderContract(
        class_name="Qwen3AsrTextRopeF32Program",
        shader_name="text_rope_f32",
        fields=(
            TensorFieldSpec(
                name="x",
                io_kind=IOKind.INPUT,
                role="input",
                contract=TensorContract(dtype="float32", shape=(1, "T", "NH")),
            ),
            TensorFieldSpec(
                name="cos",
                io_kind=IOKind.INPUT,
                role="input",
                contract=TensorContract(dtype="float32", shape=(1, "T", "D")),
            ),
            TensorFieldSpec(
                name="sin",
                io_kind=IOKind.INPUT,
                role="input",
                contract=TensorContract(dtype="float32", shape=(1, "T", "D")),
            ),
            TensorFieldSpec(
                name="output",
                io_kind=IOKind.OUTPUT,
                role="output",
                contract=TensorContract(dtype="float32", shape=(1, "T", "NH")),
            ),
        ),
        push_constants=PushConstantSpec(
            size=12,
            fields=(
                PushConstantFieldSpec("T", PushConstantType.UINT32, 0, "T"),
                PushConstantFieldSpec("NH", PushConstantType.UINT32, 4, "NH"),
                PushConstantFieldSpec("head_dim", PushConstantType.UINT32, 8, "D"),
            ),
        ),
        dispatch=(ceil_div(mul("T", "NH"), 256), 1, 1),
    ),
    source="""
#version 450

layout(std430) buffer;

layout(set = 0, binding = 0) buffer restrict readonly XBuffer {
    float x[];
};

layout(set = 0, binding = 1) buffer restrict readonly CosBuffer {
    float cos_values[];
};

layout(set = 0, binding = 2) buffer restrict readonly SinBuffer {
    float sin_values[];
};

layout(set = 0, binding = 3) buffer restrict writeonly OutputBuffer {
    float output_values[];
};

layout(push_constant) uniform PushConstants {
    uint T;
    uint NH;
    uint head_dim;
} pc;

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    const uint index = gl_GlobalInvocationID.x;
    const uint total = pc.T * pc.NH;
    if (index >= total) {
        return;
    }

    const uint token = index / pc.NH;
    const uint within_row = index - token * pc.NH;
    const uint d = within_row % pc.head_dim;
    const uint head_base = within_row - d;
    const uint half_dim = pc.head_dim / 2u;

    const float cos_val = cos_values[token * pc.head_dim + d];
    const float sin_val = sin_values[token * pc.head_dim + d];

    float partner;
    if (d < half_dim) {
        partner = -x[token * pc.NH + head_base + d + half_dim];
    } else {
        partner = x[token * pc.NH + head_base + d - half_dim];
    }

    output_values[index] = x[index] * cos_val + partner * sin_val;
}
""".lstrip(),
)
