# This file is generated by torch2vk.exportv2. Do not edit by hand.
"""Qwen3-ASR fused single-token Q/K/V projections."""

from __future__ import annotations

from torch2vk.runtime.shader import (
    IOKind,
    PushConstantFieldSpec,
    PushConstantSpec,
    PushConstantType,
    ShaderContract,
    ShaderExecutionRequirements,
    ShaderVariant,
    TensorContract,
    TensorFieldSpec,
    add,
    mul,
)
from torch2vk.vulkan.shader_execution_requirements import SubgroupRequirements


TEXT_QKV_PROJ_T1_F32 = ShaderVariant(
    name="text_qkv_proj_t1_f32",
    family="torch2vk.text",
    contract=ShaderContract(
        class_name="TextQkvProjT1F32Program",
        shader_name="text_qkv_proj_t1_f32",
        fields=(
            TensorFieldSpec(
                name="x",
                io_kind=IOKind.INPUT,
                role="input",
                contract=TensorContract(dtype="float32", shape=(1, 1, "K")),
            ),
            TensorFieldSpec(
                name="q_weight",
                io_kind=IOKind.INPUT,
                role="weight",
                contract=TensorContract(dtype="bfloat16", shape=("Q", "K")),
            ),
            TensorFieldSpec(
                name="k_weight",
                io_kind=IOKind.INPUT,
                role="weight",
                contract=TensorContract(dtype="bfloat16", shape=("KV", "K")),
            ),
            TensorFieldSpec(
                name="v_weight",
                io_kind=IOKind.INPUT,
                role="weight",
                contract=TensorContract(dtype="bfloat16", shape=("KV", "K")),
            ),
            TensorFieldSpec(
                name="q_output",
                io_kind=IOKind.OUTPUT,
                role="q_output",
                contract=TensorContract(dtype="float32", shape=(1, 1, "Q")),
            ),
            TensorFieldSpec(
                name="k_output",
                io_kind=IOKind.OUTPUT,
                role="k_output",
                contract=TensorContract(dtype="float32", shape=(1, 1, "KV")),
            ),
            TensorFieldSpec(
                name="v_output",
                io_kind=IOKind.OUTPUT,
                role="v_output",
                contract=TensorContract(dtype="float32", shape=(1, 1, "KV")),
            ),
        ),
        push_constants=PushConstantSpec(
            size=12,
            fields=(
                PushConstantFieldSpec("K", PushConstantType.UINT32, 0, "K"),
                PushConstantFieldSpec("Q", PushConstantType.UINT32, 4, "Q"),
                PushConstantFieldSpec("KV", PushConstantType.UINT32, 8, "KV"),
            ),
        ),
        dispatch=(add("Q", mul("KV", 2)), 1, 1),
    ),
    execution_requirements=ShaderExecutionRequirements(
        subgroup=SubgroupRequirements(required_size=64, require_full_subgroups=True),
        require_storage_buffer_16bit_access=True,
    ),
    source="""
#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_arithmetic : enable

layout(std430) buffer;

layout(set = 0, binding = 0) buffer restrict readonly XBuffer {
    float x[];
};

layout(set = 0, binding = 1) buffer restrict readonly QWeightBuffer {
    uint16_t q_weight[];
};

layout(set = 0, binding = 2) buffer restrict readonly KWeightBuffer {
    uint16_t k_weight[];
};

layout(set = 0, binding = 3) buffer restrict readonly VWeightBuffer {
    uint16_t v_weight[];
};

layout(set = 0, binding = 4) buffer restrict writeonly QOutputBuffer {
    float q_output[];
};

layout(set = 0, binding = 5) buffer restrict writeonly KOutputBuffer {
    float k_output[];
};

layout(set = 0, binding = 6) buffer restrict writeonly VOutputBuffer {
    float v_output[];
};

layout(push_constant) uniform PushConstants {
    uint K;
    uint Q;
    uint KV;
} pc;

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

float bf16_to_f32(uint16_t value) {
    return uintBitsToFloat(uint(value) << 16);
}

void main() {
    const uint k_lane = gl_LocalInvocationID.x;
    const uint local_col = gl_LocalInvocationID.y;
    const uint global_col = gl_WorkGroupID.x + local_col;
    const uint q_end = pc.Q;
    const uint k_end = pc.Q + pc.KV;
    const uint total = pc.Q + 2u * pc.KV;

    uint mode = 3u;
    uint col = 0u;
    if (global_col < q_end) {
        mode = 0u;
        col = global_col;
    } else if (global_col < k_end) {
        mode = 1u;
        col = global_col - q_end;
    } else if (global_col < total) {
        mode = 2u;
        col = global_col - k_end;
    }

    float acc = 0.0;
    if (mode != 3u) {
        for (uint k = k_lane; k < pc.K; k += 64u) {
            const float xv = x[k];
            const uint offset = col * pc.K + k;
            if (mode == 0u) {
                acc += xv * bf16_to_f32(q_weight[offset]);
            } else if (mode == 1u) {
                acc += xv * bf16_to_f32(k_weight[offset]);
            } else {
                acc += xv * bf16_to_f32(v_weight[offset]);
            }
        }
    }

    const float score = subgroupAdd(acc);
    if (gl_SubgroupInvocationID == 0u) {
        if (mode == 0u) {
            q_output[col] = score;
        } else if (mode == 1u) {
            k_output[col] = score;
        } else if (mode == 2u) {
            v_output[col] = score;
        }
    }
}
""".lstrip(),
)
