"""Generate Python dispatch code directly from torch.export.ExportedProgram."""

from __future__ import annotations

import torch
from torch.export import ExportedProgram
from torch.export.graph_signature import ExportGraphSignature, InputKind
from torch.fx import Graph, Node

from torch2vk.export.graph import SKIP_OPS, is_alias_op, node_input_names
from torch2vk.export.registry import DEFAULT_REGISTRY, ShaderRegistry
from torch2vk.runtime.shader import IOKind, ShaderVariant


def generate_dispatch_source(
    prog: ExportedProgram,
    *,
    class_name: str = "ExportedTensors",
    function_name: str = "run_exported",
    registry: ShaderRegistry = DEFAULT_REGISTRY,
) -> str:
    graph = prog.graph_module.graph
    sig = prog.graph_signature

    node_variants = _resolve_all_variants(graph, registry)

    lines: list[str] = []
    lines.append('"""Generated by torch2vk.export. Do not edit."""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from dataclasses import dataclass")
    lines.append("")
    lines.append("from torch2vk.runtime.logical import LogicalTensor")
    lines.append("from torch2vk.runtime.session import RuntimeSession")
    lines.append("from torch2vk.runtime.shader import ShaderVariant")
    lines.append("")
    lines.append("")
    lines.extend(_generate_param_fields(sig))
    lines.append("")
    lines.append("")
    lines.extend(_generate_dataclass(graph, sig, class_name))
    lines.append("")
    lines.append("")
    lines.extend(_generate_dispatch_function(graph, class_name, function_name, node_variants))
    lines.append("")

    return "\n".join(lines)


def _resolve_all_variants(graph: Graph, registry: ShaderRegistry) -> dict[str, ShaderVariant]:
    variants: dict[str, ShaderVariant] = {}
    for node in graph.nodes:
        if node.op != "call_function":
            continue
        target = str(node.target)
        if target in SKIP_OPS or is_alias_op(node):
            continue
        shader = registry.resolve(node)
        if shader is not None:
            variants[node.name] = shader
    return variants


def _generate_param_fields(sig: ExportGraphSignature) -> list[str]:
    lines: list[str] = []
    lines.append("PARAMETER_FIELDS = {")
    for spec in sig.input_specs:
        if spec.kind in (InputKind.PARAMETER, InputKind.BUFFER):
            lines.append(f'    "{spec.arg.name}": "{spec.target}",')
    lines.append("}")
    return lines


def _generate_dataclass(graph: Graph, sig: ExportGraphSignature, class_name: str) -> list[str]:
    lines: list[str] = []
    lines.append("@dataclass")
    lines.append(f"class {class_name}:")

    seen: set[str] = set()
    for spec in sig.input_specs:
        name = spec.arg.name
        if name not in seen:
            lines.append(f"    {name}: LogicalTensor")
            seen.add(name)

    for node in graph.nodes:
        if node.op != "call_function":
            continue
        if str(node.target) in SKIP_OPS:
            continue
        if node.name not in seen:
            lines.append(f"    {node.name}: LogicalTensor")
            seen.add(node.name)

    return lines


def _generate_dispatch_function(
    graph: Graph,
    class_name: str,
    function_name: str,
    node_variants: dict[str, ShaderVariant],
) -> list[str]:
    lines: list[str] = []
    lines.append(f"def {function_name}(rt: RuntimeSession, tensors: {class_name}, shaders: dict[str, ShaderVariant]) -> None:")

    for node in graph.nodes:
        if node.op != "call_function":
            continue
        target = str(node.target)
        if target in SKIP_OPS:
            continue

        if is_alias_op(node):
            inputs = node_input_names(node)
            src = inputs[0] if inputs else "???"
            lines.append(f"    _alias(rt, tensors.{src}, tensors.{node.name})")
            continue

        shader = node_variants.get(node.name)
        if shader is None:
            lines.append(f"    # TODO: no shader for {target} ({node.name})")
            continue

        args = _build_shader_args(node, shader)
        lines.append(f'    shaders["{node.name}"](rt, {args})')

    lines.append("")
    lines.append("")
    lines.append("def _alias(rt: RuntimeSession, src: LogicalTensor, dst: LogicalTensor) -> None:")
    lines.append("    rt._materialize_read(src)")
    lines.append("    with dst.runtime_write_scope():")
    lines.append("        dst.buffer = src.buffer")
    lines.append("        dst.descriptor_nbytes = src.descriptor_nbytes")
    lines.append("        dst.version = src.version")

    return lines


def _build_shader_args(node: Node, shader: ShaderVariant) -> str:
    contract = shader.contract
    input_fields = [f for f in contract.fields if f.io_kind == IOKind.INPUT]
    output_fields = [f for f in contract.fields if f.io_kind in (IOKind.OUTPUT, IOKind.INOUT)]

    inputs = node_input_names(node)
    parts: list[str] = []
    for i, field in enumerate(input_fields):
        if i < len(inputs):
            parts.append(f"{field.name}=tensors.{inputs[i]}")
    for i, field in enumerate(output_fields):
        if i == 0:
            parts.append(f"{field.name}=tensors.{node.name}")

    return ", ".join(parts)
