"""Dispatch code generation from exported FX graphs."""

from __future__ import annotations

import re
from collections.abc import Callable, Mapping
from dataclasses import dataclass

from torch.export import ExportedProgram
from torch.export.graph_signature import ExportGraphSignature, InputKind
from torch.fx import Graph, Node

from torch2vk.checkpoints.gguf import GGUFTensorType
from torch2vk.export._templates import render_template
from torch2vk.export.graph import SKIP_OPS, is_alias_op, node_input_names
from torch2vk.export.registry import DEFAULT_REGISTRY, ShaderRegistry
from torch2vk.export.shaders._factory import node_input_dtype, node_input_shape
from torch2vk.export.shaders.conv1d_quantized import make_conv1d_q8_0_variant
from torch2vk.export.shaders.conv2d_quantized import make_conv2d_q8_0_variant
from torch2vk.export.shaders.conv_transpose1d_quantized import (
    make_conv_transpose1d_q8_0_variant,
)
from torch2vk.export.shaders.embedding_quantized import (
    make_embedding_q4_k_m_variant,
    make_embedding_q8_0_variant,
)
from torch2vk.export.shaders.linear_bias_quantized import make_linear_bias_q8_0_variant
from torch2vk.export.shaders.linear_nobias_quantized import (
    make_linear_nobias_q4_k_m_variant,
    make_linear_nobias_q6_k_variant,
    make_linear_nobias_q8_0_variant,
)
from torch2vk.quantize import Q4KMQuantizationConfig
from torch2vk.quantize.gguf import _WeightDeclaration
from torch2vk.runtime.shader import IOKind, ShaderContract, ShaderVariant


@dataclass(frozen=True, slots=True)
class _AliasOp:
    src: str
    dst: str


@dataclass(frozen=True, slots=True)
class _DispatchOp:
    name: str
    variant: ShaderVariant
    bindings: dict[str, str]
    q6_variant: ShaderVariant | None = None
    q8_variant: ShaderVariant | None = None


@dataclass(frozen=True, slots=True)
class _UnsupportedOp:
    name: str
    message: str


_Op = _AliasOp | _DispatchOp | _UnsupportedOp


def render_dispatch_function(function_name: str, class_name: str, ops) -> str:
    return render_template(
        "dispatch_function.py.j2",
        function_name=function_name,
        class_name=class_name,
        ops=ops,
    ).rstrip("\n")


def render_dispatch_file(
    *,
    docstring: str,
    shader_package: str,
    tensor_package: str,
    shader_imports,
    tensor_imports,
    function_sources: list[str],
    extra_imports_source: str = "",
) -> str:
    return render_template(
        "dispatch_file.py.j2",
        docstring=docstring,
        shader_package=shader_package,
        tensor_package=tensor_package,
        shader_imports=shader_imports,
        tensor_imports=tensor_imports,
        extra_imports_source=extra_imports_source.rstrip("\n"),
        function_sources_source="\n\n\n".join(function_sources),
    )


def bind_dispatch_function_to_tensors(source: str) -> str:
    bound = re.sub(
        r"def (run_\w+)\(rt: RuntimeSession, tensors: (\w+)\) -> None:",
        r"def _\1_with_tensors(rt: RuntimeSession, tensors: \2) -> None:",
        source,
        count=1,
    )
    if bound == source:
        raise ValueError("generated dispatch source does not match tensor-bound signature")
    return bound


def render_model_dispatch_module(
    *,
    model_package: str,
    function_name: str,
    tensor_file: str,
    tensor_class: str,
    tensor_expr: str,
    shader_imports: Mapping[str, str],
    function_source: str,
    parameters_source: str = "",
    uses_quantized_linear_dispatch: bool = False,
) -> str:
    return render_template(
        "model_dispatch_module.py.j2",
        model_package=model_package,
        function_name=function_name,
        tensor_file=tensor_file,
        tensor_class=tensor_class,
        tensor_expr=tensor_expr,
        shader_imports=tuple(
            {"shader": shader, "const": const} for shader, const in sorted(shader_imports.items())
        ),
        function_source=function_source.rstrip("\n"),
        parameters_source=parameters_source,
        uses_quantized_linear_dispatch=uses_quantized_linear_dispatch,
    )


def generate_dispatch_source(
    prog: ExportedProgram,
    *,
    class_name: str = "ExportedTensors",
    function_name: str = "run_exported",
    registry: ShaderRegistry = DEFAULT_REGISTRY,
) -> str:
    graph = prog.graph_module.graph
    sig = prog.graph_signature

    node_variants = _resolve_all_variants(graph, registry)

    lines: list[str] = []
    lines.append('"""Generated by torch2vk.export. Do not edit."""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from dataclasses import dataclass")
    lines.append("")
    lines.append("from torch2vk.runtime.logical import LogicalTensor")
    lines.append("from torch2vk.runtime.session import RuntimeSession")
    lines.append("from torch2vk.runtime.shader import ShaderVariant")
    lines.append("")
    lines.append("")
    lines.extend(_generate_param_fields(sig))
    lines.append("")
    lines.append("")
    lines.extend(_generate_dataclass(graph, sig, class_name))
    lines.append("")
    lines.append("")
    lines.extend(_generate_dispatch_function(graph, class_name, function_name, node_variants))
    lines.append("")

    return "\n".join(lines)


def _resolve_all_variants(
    graph: Graph,
    registry: ShaderRegistry,
    *,
    parameter_map: Mapping[str, str] | None = None,
    quantization_config: Q4KMQuantizationConfig | None = None,
) -> dict[str, ShaderVariant]:
    variants: dict[str, ShaderVariant] = {}
    for node in graph.nodes:
        if node.op != "call_function":
            continue
        target = str(node.target)
        if target in SKIP_OPS or is_alias_op(node):
            continue
        shader = _resolve_variant(
            node,
            registry,
            parameter_map=parameter_map or {},
            quantization_config=quantization_config,
        )
        if shader is not None:
            variants[node.name] = shader
    return variants


def _resolve_variant(
    node: Node,
    registry: ShaderRegistry,
    *,
    parameter_map: Mapping[str, str],
    quantization_config: Q4KMQuantizationConfig | None,
) -> ShaderVariant | None:
    if quantization_config is not None:
        quantized = _resolve_quantized_variant(
            node,
            quantization_config=quantization_config,
            parameter_map=parameter_map,
            activation_dtype=registry.activation_dtype,
        )
        if quantized is not None:
            return quantized
    return registry.resolve(node)


def _resolve_quantized_variant(
    node: Node,
    *,
    quantization_config: Q4KMQuantizationConfig,
    parameter_map: Mapping[str, str],
    activation_dtype: str,
) -> ShaderVariant | None:
    target = str(node.target)
    if target == "aten.linear.default":
        return _resolve_quantized_linear_variant(
            node,
            quantization_config=quantization_config,
            parameter_map=parameter_map,
            activation_dtype=activation_dtype,
        )
    if target == "aten.embedding.default":
        return _resolve_quantized_embedding_variant(
            node,
            quantization_config=quantization_config,
            parameter_map=parameter_map,
            activation_dtype=activation_dtype,
        )
    if target == "aten.conv1d.default":
        return _resolve_quantized_q8_only_variant(
            node,
            quantization_config=quantization_config,
            parameter_map=parameter_map,
            activation_dtype=activation_dtype,
            weight_arg_index=1,
            factory=make_conv1d_q8_0_variant,
        )
    if target == "aten.conv2d.default":
        return _resolve_quantized_q8_only_variant(
            node,
            quantization_config=quantization_config,
            parameter_map=parameter_map,
            activation_dtype=activation_dtype,
            weight_arg_index=1,
            factory=make_conv2d_q8_0_variant,
        )
    if target == "aten.conv_transpose1d.default":
        return _resolve_quantized_q8_only_variant(
            node,
            quantization_config=quantization_config,
            parameter_map=parameter_map,
            activation_dtype=activation_dtype,
            weight_arg_index=1,
            factory=make_conv_transpose1d_q8_0_variant,
        )
    return None


def _resolve_quantized_linear_variant(
    node: Node,
    *,
    quantization_config: Q4KMQuantizationConfig,
    parameter_map: Mapping[str, str],
    activation_dtype: str,
) -> ShaderVariant | None:
    declaration = _quantized_weight_declaration(
        node,
        quantization_config=quantization_config,
        parameter_map=parameter_map,
        weight_arg_index=1,
    )
    if declaration is None or declaration.gguf_type is GGUFTensorType.F32:
        return None
    has_bias = len(node.args) >= 3 and isinstance(node.args[2], Node)
    if has_bias:
        if declaration.gguf_type is not GGUFTensorType.Q8_0:
            raise RuntimeError(
                f"{node.name} has quantized {declaration.gguf_type.name} linear weight with bias; "
                "only Q8_0 biased linear is supported"
            )
        return make_linear_bias_q8_0_variant(node, activation_dtype)
    checkpoint_key = _weight_checkpoint_key(node, parameter_map, 1)
    if checkpoint_key is not None and _may_need_mixed_layer_quantized_dispatch(
        checkpoint_key,
        quantization_config,
    ):
        return make_linear_nobias_q4_k_m_variant(node, activation_dtype)
    if declaration.gguf_type is GGUFTensorType.Q4_K:
        return make_linear_nobias_q4_k_m_variant(node, activation_dtype)
    if declaration.gguf_type is GGUFTensorType.Q6_K:
        return make_linear_nobias_q6_k_variant(node, activation_dtype)
    if declaration.gguf_type is GGUFTensorType.Q8_0:
        return make_linear_nobias_q8_0_variant(node, activation_dtype)
    return None


def _resolve_quantized_embedding_variant(
    node: Node,
    *,
    quantization_config: Q4KMQuantizationConfig,
    parameter_map: Mapping[str, str],
    activation_dtype: str,
) -> ShaderVariant | None:
    declaration = _quantized_weight_declaration(
        node,
        quantization_config=quantization_config,
        parameter_map=parameter_map,
        weight_arg_index=0,
    )
    if declaration is None or declaration.gguf_type is GGUFTensorType.F32:
        return None
    if declaration.gguf_type is GGUFTensorType.Q4_K:
        return make_embedding_q4_k_m_variant(node, activation_dtype)
    if declaration.gguf_type is GGUFTensorType.Q8_0:
        return make_embedding_q8_0_variant(node, activation_dtype)
    raise RuntimeError(f"{node.name} has unsupported quantized embedding weight: {declaration.gguf_type.name}")


def _resolve_quantized_q8_only_variant(
    node: Node,
    *,
    quantization_config: Q4KMQuantizationConfig,
    parameter_map: Mapping[str, str],
    activation_dtype: str,
    weight_arg_index: int,
    factory: Callable[[Node, str], ShaderVariant | None],
) -> ShaderVariant | None:
    declaration = _quantized_weight_declaration(
        node,
        quantization_config=quantization_config,
        parameter_map=parameter_map,
        weight_arg_index=weight_arg_index,
    )
    if declaration is None or declaration.gguf_type is GGUFTensorType.F32:
        return None
    if declaration.gguf_type is not GGUFTensorType.Q8_0:
        raise RuntimeError(
            f"{node.name} has unsupported quantized convolution weight: {declaration.gguf_type.name}"
        )
    return factory(node, activation_dtype)


def _quantized_weight_declaration(
    node: Node,
    *,
    quantization_config: Q4KMQuantizationConfig,
    parameter_map: Mapping[str, str],
    weight_arg_index: int,
) -> _WeightDeclaration | None:
    checkpoint_key = _weight_checkpoint_key(node, parameter_map, weight_arg_index)
    if checkpoint_key is None:
        return None
    weight_shape = node_input_shape(node, weight_arg_index)
    if not weight_shape:
        return None
    return quantization_config.declare_weight(
        checkpoint_key=checkpoint_key,
        dtype=node_input_dtype(node, weight_arg_index),
        shape=tuple(int(dim) for dim in weight_shape),
    )


def _weight_checkpoint_key(
    node: Node,
    parameter_map: Mapping[str, str],
    weight_arg_index: int,
) -> str | None:
    inputs = node_input_names(node)
    if weight_arg_index >= len(inputs):
        return None
    return parameter_map.get(inputs[weight_arg_index])


def _may_need_mixed_layer_quantized_dispatch(
    checkpoint_key: str,
    quantization_config: Q4KMQuantizationConfig,
) -> bool:
    marker = ".layers.0."
    if marker not in checkpoint_key or not quantization_config.has_q6:
        return False
    layer_prefix, suffix = checkpoint_key.split(marker, 1)
    layer_prefix = f"{layer_prefix}.layers."
    return any(
        name.startswith(layer_prefix) and name.endswith(suffix)
        for name in quantization_config.q6_tensor_names
    )


def _mixed_quantized_linear_op_names(
    graph: Graph,
    *,
    parameter_map: Mapping[str, str],
    quantization_config: Q4KMQuantizationConfig | None,
) -> frozenset[str]:
    if quantization_config is None or not quantization_config.has_q6:
        return frozenset()
    names: set[str] = set()
    for node in graph.nodes:
        if node.op != "call_function" or str(node.target) != "aten.linear.default":
            continue
        checkpoint_key = _weight_checkpoint_key(node, parameter_map, 1)
        if checkpoint_key is None:
            continue
        if _may_need_mixed_layer_quantized_dispatch(checkpoint_key, quantization_config):
            names.add(node.name)
    return frozenset(names)


def _generate_param_fields(sig: ExportGraphSignature, weight_prefix: str = "") -> list[str]:
    lines: list[str] = []
    lines.append("PARAMETER_FIELDS = {")
    for spec in sig.input_specs:
        if spec.kind in (InputKind.PARAMETER, InputKind.BUFFER):
            lines.append(f'    "{spec.arg.name}": "{weight_prefix}{spec.target}",')
    lines.append("}")
    return lines


def _parameter_map(sig: ExportGraphSignature, weight_prefix: str = "") -> dict[str, str]:
    parameter_map: dict[str, str] = {}
    for spec in sig.input_specs:
        if spec.kind in (InputKind.PARAMETER, InputKind.BUFFER):
            parameter_map[spec.arg.name] = f"{weight_prefix}{spec.target}"
    return parameter_map


def _generate_dataclass(graph: Graph, sig: ExportGraphSignature, class_name: str) -> list[str]:
    lines: list[str] = []
    lines.append("@dataclass")
    lines.append(f"class {class_name}:")

    seen: set[str] = set()
    for spec in sig.input_specs:
        name = spec.arg.name
        if name not in seen:
            lines.append(f"    {name}: LogicalTensor")
            seen.add(name)

    for node in graph.nodes:
        if node.op != "call_function":
            continue
        if str(node.target) in SKIP_OPS:
            continue
        if node.name not in seen:
            lines.append(f"    {node.name}: LogicalTensor")
            seen.add(node.name)

    return lines


def _generate_dispatch_function(
    graph: Graph,
    class_name: str,
    function_name: str,
    node_variants: dict[str, ShaderVariant],
) -> list[str]:
    lines: list[str] = []
    lines.append(
        f"def {function_name}(rt: RuntimeSession, tensors: {class_name}, shaders: dict[str, ShaderVariant]) -> None:"
    )

    for node in graph.nodes:
        if node.op != "call_function":
            continue
        target = str(node.target)
        if target in SKIP_OPS:
            continue

        if is_alias_op(node):
            continue

        shader = node_variants.get(node.name)
        if shader is None:
            message = f"unsupported exported op {target} ({node.name})"
            lines.append(f"    raise RuntimeError({message!r})")
            continue

        args = _build_shader_args(node, shader)
        lines.append(f'    shaders["{node.name}"](rt, {args})')

    return lines


def _build_shader_args(node: Node, shader: ShaderVariant) -> str:
    contract = shader.contract
    input_fields = [f for f in contract.fields if f.io_kind in (IOKind.INPUT, IOKind.INOUT)]
    output_fields = [f for f in contract.fields if f.io_kind in (IOKind.OUTPUT, IOKind.INOUT)]

    inputs = node_input_names(node)
    bindings: dict[str, str] = {}
    for i, field in enumerate(input_fields):
        if i < len(inputs):
            bindings[field.name] = f"tensors.{inputs[i]}"
    for field in output_fields:
        bindings[field.name] = f"tensors.{node.name}"

    return ", ".join(f"{k}={v}" for k, v in bindings.items())


def _generate_static_dispatch_function(
    graph: Graph,
    class_name: str,
    function_name: str,
    node_variants: dict[str, ShaderVariant],
    *,
    q6_variant_op_names: frozenset[str] = frozenset(),
) -> tuple[list[str], dict[str, str]]:
    ops = _collect_ops(graph, node_variants, q6_variant_op_names=q6_variant_op_names)
    output_names = _find_graph_outputs(graph)
    ops = _prune_dead_ops(ops, output_names)

    unsupported = [op for op in ops if isinstance(op, _UnsupportedOp)]
    if unsupported:
        details = "\n".join(f"  - {op.message}" for op in unsupported)
        raise RuntimeError(f"{function_name} contains unsupported ops:\n{details}")

    shader_imports: dict[str, str] = {}
    lines: list[str] = []
    lines.append(f"def {function_name}(rt: RuntimeSession, tensors: {class_name}) -> None:")

    for op in ops:
        if isinstance(op, _AliasOp):
            continue
        elif isinstance(op, _DispatchOp):
            const_name = op.variant.name.upper()
            shader_imports[op.variant.name] = const_name
            args = ", ".join(f"{k}={v}" for k, v in op.bindings.items())
            if op.q6_variant is not None:
                if op.q8_variant is None:
                    raise RuntimeError(f"{op.name} has q6 variant but no q8 variant")
                q6_const_name = op.q6_variant.name.upper()
                q8_const_name = op.q8_variant.name.upper()
                shader_imports[op.q6_variant.name] = q6_const_name
                shader_imports[op.q8_variant.name] = q8_const_name
                lines.append(
                    f"    run_quantized_linear(rt, q4={const_name}, q6={q6_const_name}, q8={q8_const_name}, {args})"
                )
            else:
                lines.append(f"    {const_name}(rt, {args})")
    if len(lines) == 1:
        lines.append("    pass")

    return lines, shader_imports


def _collect_ops(
    graph: Graph,
    node_variants: dict[str, ShaderVariant],
    *,
    q6_variant_op_names: frozenset[str] = frozenset(),
) -> list[_Op]:
    ops: list[_Op] = []
    seen_variants: dict[str, ShaderVariant] = {}

    for node in graph.nodes:
        if node.op != "call_function":
            continue
        target = str(node.target)
        if target in SKIP_OPS:
            continue

        if is_alias_op(node):
            inputs = node_input_names(node)
            src = inputs[0] if inputs else "???"
            ops.append(_AliasOp(src=src, dst=node.name))
            continue

        shader = node_variants.get(node.name)
        if shader is None:
            ops.append(
                _UnsupportedOp(
                    name=node.name, message=f"unsupported exported op {target} ({node.name})"
                )
            )
            continue

        q6_shader = _q6_variant_for_q4_k_m(node, shader) if node.name in q6_variant_op_names else None
        q8_shader = _q8_variant_for_q4_k_m(node, shader) if q6_shader is not None else None
        shader = _dedup_variant(shader, seen_variants)
        if q6_shader is not None:
            q6_shader = _dedup_variant(q6_shader, seen_variants)
        if q8_shader is not None:
            q8_shader = _dedup_variant(q8_shader, seen_variants)

        input_fields = [
            f for f in shader.contract.fields if f.io_kind in (IOKind.INPUT, IOKind.INOUT)
        ]
        output_fields = [
            f for f in shader.contract.fields if f.io_kind in (IOKind.OUTPUT, IOKind.INOUT)
        ]
        inputs = node_input_names(node)
        bindings: dict[str, str] = {}
        for i, field in enumerate(input_fields):
            if i < len(inputs):
                bindings[field.name] = f"tensors.{inputs[i]}"
        for field in output_fields:
            bindings[field.name] = f"tensors.{node.name}"
        ops.append(
            _DispatchOp(
                name=node.name,
                variant=shader,
                bindings=bindings,
                q6_variant=q6_shader,
                q8_variant=q8_shader,
            )
        )

    return ops


def _q6_variant_for_q4_k_m(node: Node, shader: ShaderVariant) -> ShaderVariant | None:
    base_name = _base_quantized_shader_name(shader.name)
    if base_name == "linear_nobias_q4_k_f32":
        return make_linear_nobias_q6_k_variant(node, _activation_dtype(shader), matvec=False)
    if base_name == "linear_nobias_q4_k_matvec_f32":
        return make_linear_nobias_q6_k_variant(node, _activation_dtype(shader), matvec=True)
    return None


def _q8_variant_for_q4_k_m(node: Node, shader: ShaderVariant) -> ShaderVariant | None:
    if _base_quantized_shader_name(shader.name) in {
        "linear_nobias_q4_k_f32",
        "linear_nobias_q4_k_matvec_f32",
    }:
        return make_linear_nobias_q8_0_variant(node, _activation_dtype(shader))
    return None


def _base_quantized_shader_name(name: str) -> str:
    return name.split("_act_", 1)[0]


def _activation_dtype(shader: ShaderVariant) -> str:
    field = shader.contract.input_fields[0]
    dtype = field.contract.dtype
    if not isinstance(dtype, str):
        raise TypeError(f"{shader.name} input dtype must be concrete, got {dtype}")
    return dtype


def _dedup_variant(
    shader: ShaderVariant,
    seen_variants: dict[str, ShaderVariant],
) -> ShaderVariant:
    shader_key = shader.name
    if shader_key in seen_variants:
        if seen_variants[shader_key].contract != shader.contract:
            shader_key = f"{shader.name}_{len(seen_variants)}"
            new_contract = ShaderContract(
                class_name=shader.contract.class_name,
                shader_name=shader_key,
                fields=shader.contract.fields,
                dispatch=shader.contract.dispatch,
                push_constants=shader.contract.push_constants,
                params_buffer=shader.contract.params_buffer,
            )
            shader = ShaderVariant(
                name=shader_key,
                family=shader.family,
                contract=new_contract,
                source=shader.source,
                precompiled_spv_path=shader.precompiled_spv_path,
                specialization_constants=shader.specialization_constants,
                include_dirs=shader.include_dirs,
                compile_defines=shader.compile_defines,
                execution_requirements=shader.execution_requirements,
            )
    if shader_key not in seen_variants:
        seen_variants[shader_key] = shader
    return shader


def _find_graph_outputs(graph: Graph) -> list[str]:
    names: list[str] = []
    for node in graph.nodes:
        if node.op == "output":
            _collect_output_node_names(node.args, names)
    return names


def _collect_output_node_names(value, names: list[str]) -> None:
    if isinstance(value, Node):
        names.append(value.name)
    elif isinstance(value, (list, tuple)):
        for item in value:
            _collect_output_node_names(item, names)


def _prune_dead_ops(ops: list[_Op], output_names: list[str]) -> list[_Op]:
    needed = set(output_names)
    kept_reversed: list[_Op] = []
    for op in reversed(ops):
        if isinstance(op, _DispatchOp):
            if op.name not in needed:
                continue
            kept_reversed.append(op)
            for v in op.bindings.values():
                needed.add(v.removeprefix("tensors."))
        elif isinstance(op, _AliasOp):
            if op.dst not in needed:
                continue
            kept_reversed.append(op)
            needed.add(op.src)
        elif isinstance(op, _UnsupportedOp):
            if op.name not in needed:
                continue
            kept_reversed.append(op)
    return list(reversed(kept_reversed))


def generate_dispatch_function_source(
    prog: ExportedProgram,
    *,
    class_name: str = "ExportedTensors",
    function_name: str = "run_exported",
    shader_package: str = "",
    registry: ShaderRegistry = DEFAULT_REGISTRY,
    weight_prefix: str = "",
    quantization_config: Q4KMQuantizationConfig | None = None,
) -> tuple[str, dict[str, str], dict[str, ShaderVariant]]:
    """Generate dispatch function with static shader imports.

    Returns (function_source, {shader_name: CONST_NAME}, {shader_name: ShaderVariant}).
    The caller is responsible for assembling the final file with imports.
    """
    graph = prog.graph_module.graph
    parameter_map = _parameter_map(prog.graph_signature, weight_prefix)
    node_variants = _resolve_all_variants(
        graph,
        registry,
        parameter_map=parameter_map,
        quantization_config=quantization_config,
    )
    q6_variant_op_names = _mixed_quantized_linear_op_names(
        graph,
        parameter_map=parameter_map,
        quantization_config=quantization_config,
    )
    lines, shader_imports = _generate_static_dispatch_function(
        graph,
        class_name,
        function_name,
        node_variants,
        q6_variant_op_names=q6_variant_op_names,
    )
    all_ops = _collect_ops(graph, node_variants, q6_variant_op_names=q6_variant_op_names)
    output_names = _find_graph_outputs(graph)
    live_ops = _prune_dead_ops(all_ops, output_names)
    used_variants: dict[str, ShaderVariant] = {}
    for op in live_ops:
        if isinstance(op, _DispatchOp):
            used_variants.setdefault(op.variant.name, op.variant)
            if op.q6_variant is not None:
                used_variants.setdefault(op.q6_variant.name, op.q6_variant)
            if op.q8_variant is not None:
                used_variants.setdefault(op.q8_variant.name, op.q8_variant)
    return "\n".join(lines), shader_imports, used_variants
