"""Dispatch code generation from exported FX graphs."""

from __future__ import annotations

import re
from dataclasses import dataclass
from collections.abc import Mapping

from torch.export import ExportedProgram
from torch.export.graph_signature import ExportGraphSignature, InputKind
from torch.fx import Graph, Node

from torch2vk.export._templates import render_template
from torch2vk.export.graph import SKIP_OPS, is_alias_op, node_input_names
from torch2vk.export.quantization import Q4KMWeightQuantization
from torch2vk.export.registry import DEFAULT_REGISTRY, ShaderRegistry
from torch2vk.export.shaders.linear_nobias_quantized import make_linear_nobias_q6_k_variant
from torch2vk.runtime.shader import IOKind, ShaderContract, ShaderVariant


@dataclass(frozen=True, slots=True)
class _AliasOp:
    src: str
    dst: str


@dataclass(frozen=True, slots=True)
class _DispatchOp:
    name: str
    variant: ShaderVariant
    bindings: dict[str, str]
    q6_variant: ShaderVariant | None = None


@dataclass(frozen=True, slots=True)
class _UnsupportedOp:
    name: str
    message: str


_Op = _AliasOp | _DispatchOp | _UnsupportedOp


def render_dispatch_function(function_name: str, class_name: str, ops) -> str:
    return render_template(
        "dispatch_function.py.j2",
        function_name=function_name,
        class_name=class_name,
        ops=ops,
    ).rstrip("\n")


def render_dispatch_file(
    *,
    docstring: str,
    shader_package: str,
    tensor_package: str,
    shader_imports,
    tensor_imports,
    function_sources: list[str],
    extra_imports_source: str = "",
) -> str:
    return render_template(
        "dispatch_file.py.j2",
        docstring=docstring,
        shader_package=shader_package,
        tensor_package=tensor_package,
        shader_imports=shader_imports,
        tensor_imports=tensor_imports,
        extra_imports_source=extra_imports_source.rstrip("\n"),
        function_sources_source="\n\n\n".join(function_sources),
    )


def bind_dispatch_function_to_tensors(source: str) -> str:
    bound = re.sub(
        r"def (run_\w+)\(rt: RuntimeSession, tensors: (\w+)\) -> None:",
        r"def _\1_with_tensors(rt: RuntimeSession, tensors: \2) -> None:",
        source,
        count=1,
    )
    if bound == source:
        raise ValueError("generated dispatch source does not match tensor-bound signature")
    return bound


def render_model_dispatch_module(
    *,
    model_package: str,
    function_name: str,
    tensor_file: str,
    tensor_class: str,
    tensor_expr: str,
    shader_imports: Mapping[str, str],
    function_source: str,
    parameters_source: str = "",
    uses_q4_q6_dispatch: bool = False,
) -> str:
    return render_template(
        "model_dispatch_module.py.j2",
        model_package=model_package,
        function_name=function_name,
        tensor_file=tensor_file,
        tensor_class=tensor_class,
        tensor_expr=tensor_expr,
        shader_imports=tuple(
            {"shader": shader, "const": const}
            for shader, const in sorted(shader_imports.items())
        ),
        function_source=function_source.rstrip("\n"),
        parameters_source=parameters_source,
        uses_q4_q6_dispatch=uses_q4_q6_dispatch,
    )


def generate_dispatch_source(
    prog: ExportedProgram,
    *,
    class_name: str = "ExportedTensors",
    function_name: str = "run_exported",
    registry: ShaderRegistry = DEFAULT_REGISTRY,
) -> str:
    graph = prog.graph_module.graph
    sig = prog.graph_signature

    node_variants = _resolve_all_variants(graph, registry)

    lines: list[str] = []
    lines.append('"""Generated by torch2vk.export. Do not edit."""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from dataclasses import dataclass")
    lines.append("")
    lines.append("from torch2vk.runtime.logical import LogicalTensor")
    lines.append("from torch2vk.runtime.session import RuntimeSession")
    lines.append("from torch2vk.runtime.shader import ShaderVariant")
    lines.append("")
    lines.append("")
    lines.extend(_generate_param_fields(sig))
    lines.append("")
    lines.append("")
    lines.extend(_generate_dataclass(graph, sig, class_name))
    lines.append("")
    lines.append("")
    lines.extend(_generate_dispatch_function(graph, class_name, function_name, node_variants))
    lines.append("")

    return "\n".join(lines)


def _resolve_all_variants(graph: Graph, registry: ShaderRegistry) -> dict[str, ShaderVariant]:
    variants: dict[str, ShaderVariant] = {}
    for node in graph.nodes:
        if node.op != "call_function":
            continue
        target = str(node.target)
        if target in SKIP_OPS or is_alias_op(node):
            continue
        shader = registry.resolve(node)
        if shader is not None:
            variants[node.name] = shader
    return variants


def _generate_param_fields(sig: ExportGraphSignature, weight_prefix: str = "") -> list[str]:
    lines: list[str] = []
    lines.append("PARAMETER_FIELDS = {")
    for spec in sig.input_specs:
        if spec.kind in (InputKind.PARAMETER, InputKind.BUFFER):
            lines.append(f'    "{spec.arg.name}": "{weight_prefix}{spec.target}",')
    lines.append("}")
    return lines


def _generate_dataclass(graph: Graph, sig: ExportGraphSignature, class_name: str) -> list[str]:
    lines: list[str] = []
    lines.append("@dataclass")
    lines.append(f"class {class_name}:")

    seen: set[str] = set()
    for spec in sig.input_specs:
        name = spec.arg.name
        if name not in seen:
            lines.append(f"    {name}: LogicalTensor")
            seen.add(name)

    for node in graph.nodes:
        if node.op != "call_function":
            continue
        if str(node.target) in SKIP_OPS:
            continue
        if node.name not in seen:
            lines.append(f"    {node.name}: LogicalTensor")
            seen.add(node.name)

    return lines


def _generate_dispatch_function(
    graph: Graph,
    class_name: str,
    function_name: str,
    node_variants: dict[str, ShaderVariant],
) -> list[str]:
    lines: list[str] = []
    lines.append(f"def {function_name}(rt: RuntimeSession, tensors: {class_name}, shaders: dict[str, ShaderVariant]) -> None:")

    for node in graph.nodes:
        if node.op != "call_function":
            continue
        target = str(node.target)
        if target in SKIP_OPS:
            continue

        if is_alias_op(node):
            continue

        shader = node_variants.get(node.name)
        if shader is None:
            message = f"unsupported exported op {target} ({node.name})"
            lines.append(f"    raise RuntimeError({message!r})")
            continue

        args = _build_shader_args(node, shader)
        lines.append(f'    shaders["{node.name}"](rt, {args})')

    return lines


def _build_shader_args(node: Node, shader: ShaderVariant) -> str:
    contract = shader.contract
    input_fields = [f for f in contract.fields if f.io_kind in (IOKind.INPUT, IOKind.INOUT)]
    output_fields = [f for f in contract.fields if f.io_kind in (IOKind.OUTPUT, IOKind.INOUT)]

    inputs = node_input_names(node)
    bindings: dict[str, str] = {}
    for i, field in enumerate(input_fields):
        if i < len(inputs):
            bindings[field.name] = f"tensors.{inputs[i]}"
    for field in output_fields:
        bindings[field.name] = f"tensors.{node.name}"

    return ", ".join(f"{k}={v}" for k, v in bindings.items())


def _generate_static_dispatch_function(
    graph: Graph,
    class_name: str,
    function_name: str,
    node_variants: dict[str, ShaderVariant],
    *,
    q4_k_m_has_q6: bool = False,
) -> tuple[list[str], dict[str, str]]:
    ops = _collect_ops(graph, node_variants, q4_k_m_has_q6=q4_k_m_has_q6)
    output_names = _find_graph_outputs(graph)
    ops = _prune_dead_ops(ops, output_names)

    unsupported = [op for op in ops if isinstance(op, _UnsupportedOp)]
    if unsupported:
        details = "\n".join(f"  - {op.message}" for op in unsupported)
        raise RuntimeError(
            f"{function_name} contains unsupported ops:\n{details}"
        )

    shader_imports: dict[str, str] = {}
    lines: list[str] = []
    if any(isinstance(op, _DispatchOp) and op.q6_variant is not None for op in ops):
        lines.extend((
            "def _linear_q4_or_q6(",
            "    rt: RuntimeSession,",
            "    *,",
            "    q4: ShaderVariant,",
            "    q6: ShaderVariant,",
            "    x: LogicalTensor,",
            "    weight: LogicalTensor,",
            "    output: LogicalTensor,",
            ") -> None:",
            "    if isinstance(weight.layout, Q6KHalfwordsLayout):",
            "        q6(rt, x=x, weight=weight, output=output)",
            "        return",
            "    if not isinstance(weight.layout, Q4KWordsLayout):",
            "        raise ValueError(f\"{weight.name} expected Q4_K or Q6_K layout, got {weight.layout}\")",
            "    q4(rt, x=x, weight=weight, output=output)",
            "",
            "",
        ))
    lines.append(f"def {function_name}(rt: RuntimeSession, tensors: {class_name}) -> None:")

    for op in ops:
        if isinstance(op, _AliasOp):
            continue
        elif isinstance(op, _DispatchOp):
            const_name = op.variant.name.upper()
            shader_imports[op.variant.name] = const_name
            args = ", ".join(f"{k}={v}" for k, v in op.bindings.items())
            if op.q6_variant is not None:
                q6_const_name = op.q6_variant.name.upper()
                shader_imports[op.q6_variant.name] = q6_const_name
                lines.append(f"    _linear_q4_or_q6(rt, q4={const_name}, q6={q6_const_name}, {args})")
            else:
                lines.append(f"    {const_name}(rt, {args})")
    if len(lines) == 1:
        lines.append("    pass")

    return lines, shader_imports


def _collect_ops(
    graph: Graph,
    node_variants: dict[str, ShaderVariant],
    *,
    q4_k_m_has_q6: bool = False,
) -> list[_Op]:
    ops: list[_Op] = []
    seen_variants: dict[str, ShaderVariant] = {}

    for node in graph.nodes:
        if node.op != "call_function":
            continue
        target = str(node.target)
        if target in SKIP_OPS:
            continue

        if is_alias_op(node):
            inputs = node_input_names(node)
            src = inputs[0] if inputs else "???"
            ops.append(_AliasOp(src=src, dst=node.name))
            continue

        shader = node_variants.get(node.name)
        if shader is None:
            ops.append(_UnsupportedOp(name=node.name, message=f"unsupported exported op {target} ({node.name})"))
            continue

        q6_shader = _q6_variant_for_q4_k_m(node, shader) if q4_k_m_has_q6 else None
        shader = _dedup_variant(shader, seen_variants)
        if q6_shader is not None:
            q6_shader = _dedup_variant(q6_shader, seen_variants)

        input_fields = [f for f in shader.contract.fields if f.io_kind in (IOKind.INPUT, IOKind.INOUT)]
        output_fields = [f for f in shader.contract.fields if f.io_kind in (IOKind.OUTPUT, IOKind.INOUT)]
        inputs = node_input_names(node)
        bindings: dict[str, str] = {}
        for i, field in enumerate(input_fields):
            if i < len(inputs):
                bindings[field.name] = f"tensors.{inputs[i]}"
        for field in output_fields:
            bindings[field.name] = f"tensors.{node.name}"
        ops.append(_DispatchOp(name=node.name, variant=shader, bindings=bindings, q6_variant=q6_shader))

    return ops


def _q6_variant_for_q4_k_m(node: Node, shader: ShaderVariant) -> ShaderVariant | None:
    if shader.name == "linear_nobias_q4_k_f32":
        return make_linear_nobias_q6_k_variant(node, _activation_dtype(shader), matvec=False)
    if shader.name == "linear_nobias_q4_k_matvec_f32":
        return make_linear_nobias_q6_k_variant(node, _activation_dtype(shader), matvec=True)
    return None


def _activation_dtype(shader: ShaderVariant) -> str:
    field = shader.contract.input_fields[0]
    dtype = field.contract.dtype
    if not isinstance(dtype, str):
        raise TypeError(f"{shader.name} input dtype must be concrete, got {dtype}")
    return dtype


def _dedup_variant(
    shader: ShaderVariant,
    seen_variants: dict[str, ShaderVariant],
) -> ShaderVariant:
    shader_key = shader.name
    if shader_key in seen_variants:
        if seen_variants[shader_key].contract != shader.contract:
            shader_key = f"{shader.name}_{len(seen_variants)}"
            new_contract = ShaderContract(
                class_name=shader.contract.class_name,
                shader_name=shader_key,
                fields=shader.contract.fields,
                dispatch=shader.contract.dispatch,
                push_constants=shader.contract.push_constants,
                params_buffer=shader.contract.params_buffer,
            )
            shader = ShaderVariant(
                name=shader_key, family=shader.family, contract=new_contract,
                source=shader.source, precompiled_spv_path=shader.precompiled_spv_path,
                specialization_constants=shader.specialization_constants,
                include_dirs=shader.include_dirs, compile_defines=shader.compile_defines,
                execution_requirements=shader.execution_requirements,
            )
    if shader_key not in seen_variants:
        seen_variants[shader_key] = shader
    return shader


def _find_graph_outputs(graph: Graph) -> list[str]:
    names: list[str] = []
    for node in graph.nodes:
        if node.op == "output":
            _collect_output_node_names(node.args, names)
    return names


def _collect_output_node_names(value, names: list[str]) -> None:
    if isinstance(value, Node):
        names.append(value.name)
    elif isinstance(value, (list, tuple)):
        for item in value:
            _collect_output_node_names(item, names)


def _prune_dead_ops(ops: list[_Op], output_names: list[str]) -> list[_Op]:
    needed = set(output_names)
    kept_reversed: list[_Op] = []
    for op in reversed(ops):
        if isinstance(op, _DispatchOp):
            if op.name not in needed:
                continue
            kept_reversed.append(op)
            for v in op.bindings.values():
                needed.add(v.removeprefix("tensors."))
        elif isinstance(op, _AliasOp):
            if op.dst not in needed:
                continue
            kept_reversed.append(op)
            needed.add(op.src)
        elif isinstance(op, _UnsupportedOp):
            if op.name not in needed:
                continue
            kept_reversed.append(op)
    return list(reversed(kept_reversed))


def generate_dispatch_function_source(
    prog: ExportedProgram,
    *,
    class_name: str = "ExportedTensors",
    function_name: str = "run_exported",
    shader_package: str = "",
    registry: ShaderRegistry = DEFAULT_REGISTRY,
    weight_quantization: Q4KMWeightQuantization | None = None,
) -> tuple[str, dict[str, str], dict[str, ShaderVariant]]:
    """Generate dispatch function with static shader imports.

    Returns (function_source, {shader_name: CONST_NAME}, {shader_name: ShaderVariant}).
    The caller is responsible for assembling the final file with imports.
    """
    graph = prog.graph_module.graph
    node_variants = _resolve_all_variants(graph, registry)
    q4_k_m_has_q6 = weight_quantization is not None and weight_quantization.has_q6
    lines, shader_imports = _generate_static_dispatch_function(
        graph, class_name, function_name, node_variants, q4_k_m_has_q6=q4_k_m_has_q6,
    )
    all_ops = _collect_ops(graph, node_variants, q4_k_m_has_q6=q4_k_m_has_q6)
    output_names = _find_graph_outputs(graph)
    live_ops = _prune_dead_ops(all_ops, output_names)
    used_variants: dict[str, ShaderVariant] = {}
    for op in live_ops:
        if isinstance(op, _DispatchOp):
            used_variants.setdefault(op.variant.name, op.variant)
            if op.q6_variant is not None:
                used_variants.setdefault(op.q6_variant.name, op.q6_variant)
    return "\n".join(lines), shader_imports, used_variants
