"""Jinja-backed file rendering and generated-file writes."""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
import json
from pathlib import Path
import subprocess
import sys
from typing import Any

from jinja2 import Environment, FileSystemLoader, StrictUndefined


_GENERATED_HEADER = "# This file is generated by torch2vk.export. Do not edit by hand.\n"


@dataclass(frozen=True, slots=True)
class RenderedFile:
    relative_path: Path
    content: str


@dataclass(frozen=True, slots=True)
class ExportWriteResult:
    written: tuple[Path, ...]
    unchanged: tuple[Path, ...]
    checked_different: tuple[Path, ...]
    dry_run: bool = False


class ExportCheckError(RuntimeError):
    """Raised when generated output differs while running in check mode."""

    def __init__(self, paths: tuple[Path, ...]) -> None:
        super().__init__(
            "generated files are out of date: " + ", ".join(str(path) for path in paths)
        )
        self.paths = paths


class TemplateRenderer:
    """Small wrapper around Jinja2 with strict undefined variables."""

    def __init__(self, template_root: Path) -> None:
        self._env = Environment(
            loader=FileSystemLoader(str(template_root)),
            undefined=StrictUndefined,
            autoescape=False,
            keep_trailing_newline=True,
            trim_blocks=True,
            lstrip_blocks=True,
        )
        self._env.filters["pyrepr"] = _python_literal

    def render(
        self,
        template_name: str,
        relative_path: str | Path,
        **context: Any,
    ) -> RenderedFile:
        template = self._env.get_template(template_name)
        text = template.render(**context)
        return RenderedFile(
            relative_path=Path(relative_path),
            content=_normalize_generated_python(text),
        )


def write_rendered_files(
    files: list[RenderedFile],
    output_dir: str | Path,
    *,
    check: bool = False,
    dry_run: bool = False,
) -> ExportWriteResult:
    root = Path(output_dir)
    written: list[Path] = []
    unchanged: list[Path] = []
    checked_different: list[Path] = []

    for rendered in files:
        path = root / rendered.relative_path
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == rendered.content:
            unchanged.append(path)
            continue
        if check:
            checked_different.append(path)
            continue
        if not dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered.content, encoding="utf-8")
        written.append(path)

    if checked_different:
        raise ExportCheckError(tuple(checked_different))

    return ExportWriteResult(
        written=tuple(written),
        unchanged=tuple(unchanged),
        checked_different=tuple(checked_different),
        dry_run=dry_run,
    )


def remove_stale_files(
    output_dir: str | Path,
    stale_files: Iterable[Path],
    *,
    check: bool,
    dry_run: bool,
) -> None:
    root = Path(output_dir)
    existing = tuple(root / relative for relative in stale_files if (root / relative).exists())
    if check and existing:
        raise ExportCheckError(existing)
    if dry_run:
        return
    for path in existing:
        path.unlink()


def format_python_source(source: str, *, filename: str | Path) -> str:
    """Format generated Python source using the repository Ruff configuration."""
    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "format",
            "--stdin-filename",
            str(filename),
            "-",
        ],
        input=source,
        text=True,
        capture_output=True,
        cwd=_find_project_root(Path(filename)),
        check=False,
    )
    if completed.returncode != 0:
        raise RuntimeError(f"ruff format failed for {filename}:\n{completed.stderr.strip()}")
    return completed.stdout


def _normalize_generated_python(text: str) -> str:
    text = text.rstrip() + "\n"
    if text.startswith(_GENERATED_HEADER):
        return text
    return _GENERATED_HEADER + text


def _python_literal(value: object) -> str:
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, tuple):
        inner = ", ".join(_python_literal(item) for item in value)
        if len(value) == 1:
            inner += ","
        return f"({inner})"
    if isinstance(value, list):
        return "[" + ", ".join(_python_literal(item) for item in value) + "]"
    return repr(value)


def _find_project_root(filename: Path) -> Path | None:
    path = filename if filename.is_absolute() else Path.cwd() / filename
    for parent in (path.parent, *path.parents):
        if (parent / "pyproject.toml").exists():
            return parent
    return None
