# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice argmax select apply fused s shader scaffold."""

from __future__ import annotations

from torch2vk.runtime.shader import (  # noqa: F401
    IOKind,
    ParamsBufferFieldSpec,
    ParamsBufferSpec,
    PushConstantFieldSpec,
    PushConstantSpec,
    PushConstantType,
    ShaderContract,
    ShaderExecutionRequirements,
    ShaderVariant,
    TensorContract,
    TensorFieldSpec,
    ceil_div,
)


OMNIVOICE_ARGMAX_SELECT_APPLY_FUSED_S = ShaderVariant(
    name="omnivoice_argmax_select_apply_fused_s",
    family="omnivoice.token_select",
    contract=ShaderContract(
        class_name="OmniVoiceArgmaxSelectApplyFusedSProgram",
        shader_name="omnivoice_argmax_select_apply_fused_s",
        fields=(
            TensorFieldSpec(
                name="output_updated_ids",
                io_kind=IOKind.OUTPUT,
                role="output_updated_ids",
                contract=TensorContract(
                    dtype="int32",
                    shape=("B", "C", "S"),
                ),
            ),
            TensorFieldSpec(
                name="output_selected_flat_index",
                io_kind=IOKind.OUTPUT,
                role="output_selected_flat_index",
                contract=TensorContract(
                    dtype="int32",
                    shape=("B",),
                ),
            ),
            TensorFieldSpec(
                name="output_selected_score",
                io_kind=IOKind.OUTPUT,
                role="output_selected_score",
                contract=TensorContract(
                    dtype="float32",
                    shape=("B",),
                ),
            ),
            TensorFieldSpec(
                name="output_selected_candidate_id",
                io_kind=IOKind.OUTPUT,
                role="output_selected_candidate_id",
                contract=TensorContract(
                    dtype="int32",
                    shape=("B",),
                ),
            ),
            TensorFieldSpec(
                name="logits",
                io_kind=IOKind.INPUT,
                role="logits",
                contract=TensorContract(
                    dtype="float32",
                    shape=("B", "C", "S", "V"),
                ),
            ),
            TensorFieldSpec(
                name="codebook_offsets",
                io_kind=IOKind.INPUT,
                role="codebook_offsets",
                contract=TensorContract(
                    dtype="int32",
                    shape=("C",),
                ),
            ),
            TensorFieldSpec(
                name="penalty",
                io_kind=IOKind.INPUT,
                role="penalty",
                contract=TensorContract(
                    dtype="float32",
                    shape=("B", "C"),
                ),
            ),
            TensorFieldSpec(
                name="current_ids",
                io_kind=IOKind.INPUT,
                role="current_ids",
                contract=TensorContract(
                    dtype="int32",
                    shape=("B", "C", "S"),
                ),
            ),
        ),
        dispatch=(1, 1, "B"),
        params_buffer=ParamsBufferSpec(
            size=16,
            fields=(
                ParamsBufferFieldSpec(
                    "steps",
                    PushConstantType.UINT32,
                    0,
    "S",
                ),
                ParamsBufferFieldSpec(
                    "codebooks",
                    PushConstantType.UINT32,
                    4,
    "C",
                ),
                ParamsBufferFieldSpec(
                    "batches",
                    PushConstantType.UINT32,
                    8,
    "B",
                ),
                ParamsBufferFieldSpec(
                    "vocab",
                    PushConstantType.UINT32,
                    12,
    "V",
                ),
            ),
            binding_index=8,
        ),
    ),

    source="""
#version 460

layout(std430) buffer;

layout(set = 0, binding = 0) buffer restrict writeonly OutputUpdatedIdsBuffer { int t_output_updated_ids[]; };
layout(set = 0, binding = 1) buffer restrict writeonly OutputSelectedFlatIndexBuffer { int t_output_selected_flat_index[]; };
layout(set = 0, binding = 2) buffer restrict writeonly OutputSelectedScoreBuffer { float t_output_selected_score[]; };
layout(set = 0, binding = 3) buffer restrict writeonly OutputSelectedCandidateIdBuffer { int t_output_selected_candidate_id[]; };
layout(set = 0, binding = 4) buffer restrict readonly LogitsBuffer { float t_logits[]; };
layout(set = 0, binding = 5) buffer restrict readonly CodebookOffsetsBuffer { int t_codebook_offsets[]; };
layout(set = 0, binding = 6) buffer restrict readonly PenaltyBuffer { float t_penalty[]; };
layout(set = 0, binding = 7) buffer restrict readonly CurrentIdsBuffer { int t_current_ids[]; };
layout(set = 0, binding = 8) buffer restrict readonly sizes_UBO { ivec4 sizes; };

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

shared float s_reduce_best_score[128];
shared int s_reduce_best_cs[128];
shared int s_selected_cs;
shared int s_selected_id;
shared float s_selected_penalized_score;

void main() {
    const uint batch = gl_WorkGroupID.z;
    const uint lane = gl_LocalInvocationID.x;
    const uint steps = uint(sizes.x);
    const uint codebooks = uint(sizes.y);
    const uint batches = uint(sizes.z);
    const uint vocab = uint(sizes.w);
    if (batch >= batches) {
        return;
    }

    const uint cs_len = codebooks * steps;
    const uint logits_batch_base = batch * steps * vocab;

    float reduce_best = -3.402823466e38;
    int reduce_cs = 0;
    for (uint cs = lane; cs < cs_len; cs += 128u) {
        const uint codebook = cs / steps;
        const uint step = cs - codebook * steps;
        const int start = t_codebook_offsets[codebook];
        const int end = (codebook + 1u < codebooks) ? t_codebook_offsets[codebook + 1u] : int(vocab);
        const int seg_len = max(0, end - start);
        const uint logits_base = logits_batch_base + step * vocab;
        float best_val = -3.402823466e38;
        for (int i = 0; i < seg_len; ++i) {
            const float v = t_logits[logits_base + uint(start + i)];
            if (v > best_val) {
                best_val = v;
            }
        }
        const float penalized = best_val - t_penalty[codebook];
        if (penalized > reduce_best) {
            reduce_best = penalized;
            reduce_cs = int(cs);
        }
    }
    s_reduce_best_score[lane] = reduce_best;
    s_reduce_best_cs[lane] = reduce_cs;
    barrier();

    for (uint stride = 64u; stride > 0u; stride >>= 1u) {
        if (lane < stride) {
            const float other = s_reduce_best_score[lane + stride];
            if (other > s_reduce_best_score[lane]) {
                s_reduce_best_score[lane] = other;
                s_reduce_best_cs[lane] = s_reduce_best_cs[lane + stride];
            }
        }
        barrier();
    }

    if (lane == 0u) {
        const int selected_cs = s_reduce_best_cs[0];
        const uint selected_codebook = uint(selected_cs) / steps;
        const uint selected_step = uint(selected_cs) - selected_codebook * steps;
        const int start = t_codebook_offsets[selected_codebook];
        const int end = (selected_codebook + 1u < codebooks) ? t_codebook_offsets[selected_codebook + 1u] : int(vocab);
        const int seg_len = max(0, end - start);
        const uint logits_base = logits_batch_base + selected_step * vocab;
        float best_val = -3.402823466e38;
        int best_id = 0;
        for (int i = 0; i < seg_len; ++i) {
            const float v = t_logits[logits_base + uint(start + i)];
            if (v > best_val) {
                best_val = v;
                best_id = i;
            }
        }
        s_selected_cs = selected_cs;
        s_selected_id = best_id;
        s_selected_penalized_score = s_reduce_best_score[0];
        t_output_selected_flat_index[batch] = selected_cs;
        t_output_selected_score[batch] = s_selected_penalized_score;
        t_output_selected_candidate_id[batch] = best_id;
    }
    barrier();

    for (uint cs = lane; cs < cs_len; cs += 128u) {
        const uint codebook = cs / steps;
        const uint step = cs - codebook * steps;
        const uint out_idx = (batch * codebooks + codebook) * steps + step;
        t_output_updated_ids[out_idx] = (int(cs) == s_selected_cs) ? s_selected_id : t_current_ids[out_idx];
    }
}
""".lstrip(),
)


__all__ = [
    "OMNIVOICE_ARGMAX_SELECT_APPLY_FUSED_S",
]
