# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice audio head scalar f16 f32 f32 shader scaffold."""

from __future__ import annotations

from torch2vk.runtime.shader import ShaderContract, ShaderVariant


OMNIVOICE_AUDIO_HEAD_SCALAR_F16_F32_F32 = ShaderVariant(
    name="omnivoice_audio_head_scalar_f16_f32_f32",
    family="omnivoice.text",
    contract=ShaderContract(
        class_name="OmniVoiceAudioHeadScalarF16F32F32Program",
        shader_name="omnivoice_audio_head_scalar_f16_f32_f32",
        fields=(),
        dispatch=(1, 1, 1),
    ),
    source="""
#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_16bit_storage : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) readonly buffer W { float16_t weight[]; };
layout(binding = 1) readonly buffer X { float x[]; };
layout(binding = 2) writeonly buffer Y { float y[]; };

float fp16_bits_to_fp32(uint h) {
    uint sign = (h & 0x8000u) << 16;
    uint exp = (h >> 10) & 0x1fu;
    uint mant = h & 0x03ffu;
    if (exp == 0u) {
        if (mant == 0u) {
            return uintBitsToFloat(sign);
        }
        float value = float(mant) * exp2(-24.0);
        return sign == 0u ? value : -value;
    }
    if (exp == 31u) {
        return uintBitsToFloat(sign | 0x7f800000u | (mant << 13));
    }
    uint fp32_exp = exp + 112u;
    return uintBitsToFloat(sign | (fp32_exp << 23) | (mant << 13));
}

float round_fp16(float value) {
    uint bits = floatBitsToUint(value);
    uint sign = (bits >> 16) & 0x8000u;
    uint abs_bits = bits & 0x7fffffffu;
    uint exp = (abs_bits >> 23) & 0xffu;
    uint mant = abs_bits & 0x7fffffu;

    if (exp == 255u) {
        return value;
    }

    int half_exp = int(exp) - 127 + 15;
    if (half_exp >= 31) {
        return fp16_bits_to_fp32(sign | 0x7c00u);
    }
    if (half_exp <= 0) {
        if (half_exp < -10) {
            return fp16_bits_to_fp32(sign);
        }
        uint mantissa = mant | 0x800000u;
        uint shift = uint(14 - half_exp);
        uint half_mant = mantissa >> shift;
        uint round_bit = (mantissa >> (shift - 1u)) & 1u;
        uint sticky = mantissa & ((1u << (shift - 1u)) - 1u);
        if (round_bit != 0u && (sticky != 0u || (half_mant & 1u) != 0u)) {
            half_mant += 1u;
        }
        return fp16_bits_to_fp32(sign | half_mant);
    }

    uint half_mant = mant >> 13;
    uint round_bits = mant & 0x1fffu;
    if (round_bits > 0x1000u || (round_bits == 0x1000u && (half_mant & 1u) != 0u)) {
        half_mant += 1u;
        if (half_mant == 0x400u) {
            half_mant = 0u;
            half_exp += 1;
            if (half_exp >= 31) {
                return fp16_bits_to_fp32(sign | 0x7c00u);
            }
        }
    }

    return fp16_bits_to_fp32(sign | (uint(half_exp) << 10) | half_mant);
}

void main() {
    const uint n = gl_GlobalInvocationID.x;
    const uint s = gl_GlobalInvocationID.y;
    const uint b = gl_GlobalInvocationID.z;
    float acc = 0.0;
    for (uint k = 0; k < 1024; ++k) {
        const float xv = round_fp16(x[(b * 8 + s) * 1024 + k]);
        acc = acc + float(weight[n * 1024 + k]) * xv;
    }
    y[(b * 8 + s) * 8200 + n] = round_fp16(acc);
}
""".lstrip(),
)


__all__ = [
    "OMNIVOICE_AUDIO_HEAD_SCALAR_F16_F32_F32",
]
