# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice audio embedding sum f32 shader scaffold."""

from __future__ import annotations

from torch2vk.runtime.shader import (  # noqa: F401
    IOKind,
    ParamsBufferFieldSpec,
    ParamsBufferSpec,
    PushConstantFieldSpec,
    PushConstantSpec,
    PushConstantType,
    ShaderContract,
    ShaderExecutionRequirements,
    ShaderVariant,
    TensorContract,
    TensorFieldSpec,
    ceil_div,
)


OMNIVOICE_AUDIO_EMBEDDING_SUM_F32 = ShaderVariant(
    name="omnivoice_audio_embedding_sum_f32",
    family="omnivoice.text",
    contract=ShaderContract(
        class_name="OmniVoiceAudioEmbeddingSumF32Program",
        shader_name="omnivoice_audio_embedding_sum_f32",
        fields=(
            TensorFieldSpec(
                name="input_ids",
                io_kind=IOKind.INPUT,
                role="input_ids",
                contract=TensorContract(dtype="int64", shape=("B", "C", "T")),
            ),
            TensorFieldSpec(
                name="audio_mask",
                io_kind=IOKind.INPUT,
                role="audio_mask",
                contract=TensorContract(dtype="bool", shape=("B", "T")),
            ),
            TensorFieldSpec(
                name="codebook_layer_offsets",
                io_kind=IOKind.INPUT,
                role="codebook_layer_offsets",
                contract=TensorContract(dtype="int64", shape=("C",)),
            ),
            TensorFieldSpec(
                name="audio_embeddings_weight",
                io_kind=IOKind.INPUT,
                role="audio_embeddings_weight",
                contract=TensorContract(dtype="float32", shape=("E", "H")),
            ),
            TensorFieldSpec(
                name="output",
                io_kind=IOKind.OUTPUT,
                role="output",
                contract=TensorContract(dtype="float32", shape=("B", "T", "H")),
            ),
        ),
        push_constants=PushConstantSpec(
            size=16,
            fields=(
                PushConstantFieldSpec("C", PushConstantType.UINT32, 0, "C"),
                PushConstantFieldSpec("T", PushConstantType.UINT32, 4, "T"),
                PushConstantFieldSpec("H", PushConstantType.UINT32, 8, "H"),
                PushConstantFieldSpec("E", PushConstantType.UINT32, 12, "E"),
            ),
        ),
        dispatch=(ceil_div("H", 256), "T", "B"),
    ),
    execution_requirements=ShaderExecutionRequirements(require_shader_int64=True),

    source="""
#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

layout(std430) buffer;

layout(set = 0, binding = 0) buffer restrict readonly InputIdsBuffer {
    int64_t input_ids[];
};

layout(set = 0, binding = 1) buffer restrict readonly AudioMaskBuffer {
    bool audio_mask[];
};

layout(set = 0, binding = 2) buffer restrict readonly CodebookOffsetsBuffer {
    int64_t codebook_layer_offsets[];
};

layout(set = 0, binding = 3) buffer restrict readonly AudioEmbeddingsBuffer {
    float audio_embeddings_weight[];
};

layout(set = 0, binding = 4) buffer restrict writeonly OutputBuffer {
    float output_values[];
};

layout(push_constant) uniform PushConstants {
    uint C;
    uint T;
    uint H;
    uint E;
} pc;

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    const uint h = gl_GlobalInvocationID.x;
    const uint token = gl_GlobalInvocationID.y;
    const uint batch = gl_GlobalInvocationID.z;
    if (h >= pc.H || token >= pc.T) {
        return;
    }

    const int64_t mask = audio_mask[batch * pc.T + token] ? int64_t(1) : int64_t(0);
    float acc = 0.0;
    for (uint codebook = 0u; codebook < pc.C; ++codebook) {
        const uint id_index = (batch * pc.C + codebook) * pc.T + token;
        const int64_t shifted_id = input_ids[id_index] * mask + codebook_layer_offsets[codebook];
        if (shifted_id >= int64_t(0) && shifted_id < int64_t(pc.E)) {
            acc += audio_embeddings_weight[uint(shifted_id) * pc.H + h];
        }
    }
    output_values[(batch * pc.T + token) * pc.H + h] = acc;
}
""".lstrip(),
)


__all__ = [
    "OMNIVOICE_AUDIO_EMBEDDING_SUM_F32",
]
