# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice audio codec decoder conv1d k1 f32 shader scaffold."""

from __future__ import annotations

from torch2vk.runtime.shader import ShaderContract, ShaderVariant


OMNIVOICE_AUDIO_CODEC_DECODER_CONV1D_K1_F32 = ShaderVariant(
    name="omnivoice_audio_codec_decoder_conv1d_k1_f32",
    family="omnivoice.audio_codec",
    contract=ShaderContract(
        class_name="OmniVoiceAudioCodecDecoderConv1dK1F32Program",
        shader_name="omnivoice_audio_codec_decoder_conv1d_k1_f32",
        fields=(),
        dispatch=(1, 1, 1),
    ),
    source="""
#version 460

layout(std430) buffer;
layout(set = 0, binding = 0) buffer restrict writeonly OutputBuffer { float t_output[]; };
layout(set = 0, binding = 1) buffer restrict readonly XBuffer { float t_x[]; };
layout(set = 0, binding = 2) buffer restrict readonly WeightBuffer { float t_weight[]; };
layout(set = 0, binding = 3) buffer restrict readonly BiasBuffer { float t_bias[]; };
layout(set = 0, binding = 4) uniform restrict readonly sizes_UBO { ivec4 sizes; };

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

void main() {
    const uint oc = gl_GlobalInvocationID.x;
    const uint t = gl_GlobalInvocationID.y;
    const uint b = gl_GlobalInvocationID.z;
    const uint steps = uint(sizes.x);
    const uint batches = uint(sizes.y);
    const uint in_channels = uint(sizes.z);
    const uint out_channels = uint(sizes.w);
    if (oc >= out_channels || t >= steps || b >= batches) {
        return;
    }
    float acc = t_bias[oc];
    for (uint ic = 0u; ic < in_channels; ++ic) {
        const uint x_idx = (b * steps + t) * in_channels + ic;
        const uint w_idx = (oc * in_channels + ic);
        acc += t_x[x_idx] * t_weight[w_idx];
    }
    const uint out_idx = (b * steps + t) * out_channels + oc;
    t_output[out_idx] = acc;
}
""".lstrip(),
)


__all__ = [
    "OMNIVOICE_AUDIO_CODEC_DECODER_CONV1D_K1_F32",
]
