"""Small generated Python package/module helpers."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from torch2vk.exportv2.writer import RenderedFile, format_python_source


@dataclass(frozen=True, slots=True)
class PythonImportDecl:
    module: str
    names: tuple[str, ...]


def render_python_init_file(
    *,
    relative_path: str | Path,
    docstring: str,
    imports: tuple[PythonImportDecl, ...],
) -> RenderedFile:
    path = Path(relative_path)
    source = _render_python_init_source(docstring=docstring, imports=imports)
    return RenderedFile(
        relative_path=path,
        content=format_python_source(source, filename=path),
    )


def _render_python_init_source(
    *,
    docstring: str,
    imports: tuple[PythonImportDecl, ...],
) -> str:
    all_names = tuple(name for item in imports for name in item.names)
    lines: list[str] = [
        "# This file is generated by torch2vk.exportv2. Do not edit by hand.",
        f'"""{docstring}"""',
        "",
    ]
    for item in imports:
        lines.append(f"from {item.module} import (")
        lines.extend(f"    {name}," for name in item.names)
        lines.append(")")
    lines.extend(
        [
            "",
            "__all__ = [",
            *(f"    {name!r}," for name in all_names),
            "]",
            "",
        ]
    )
    return "\n".join(lines)
