# This file is generated by torch2vk.exportv2. Do not edit by hand.
"""Shared helpers for generated OmniVoice frame scaffolds."""

from __future__ import annotations

from dataclasses import dataclass

from torch2vk.runtime.session import RuntimeSession


@dataclass(frozen=True, slots=True)
class OmniVoiceTorchOp:
    target: str
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    note: str = ""
    name: str = ""
    op: str = "call_function"
    args: tuple[object, ...] = ()
    kwargs: tuple[tuple[str, object], ...] = ()
    shape: tuple[int, ...] | None = None
    dtype: str | None = None


def omnivoice_frame(
    rt: RuntimeSession,
    name: str,
    *,
    pytorch_compare: bool = True,
    pytorch_input_prefixes: tuple[str, ...] = (),
):
    if not pytorch_compare:
        return rt.frame(name)

    from omnivoice.models.omnivoice import OmniVoice

    return rt.frame(
        name,
        pytorch_model_class=OmniVoice,
        pytorch_input_prefixes=pytorch_input_prefixes,
    )
