# This file is generated by torch2vk.export. Do not edit by hand.
"""Shared helpers for generated OmniVoice frame scaffolds."""

from __future__ import annotations

from dataclasses import dataclass

from torch2vk.runtime.session import RuntimeSession


@dataclass(frozen=True, slots=True)
class OmniVoiceFrameStep:
    op: str
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    note: str = ""


def omnivoice_frame(rt: RuntimeSession, name: str, *, pytorch_compare: bool = True):
    if not pytorch_compare:
        return rt.frame(name)

    from omnivoice.models.omnivoice import OmniVoice

    return rt.frame(
        name,
        pytorch_model_class=OmniVoice,
    )
