# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice audio codec decode frame scaffold."""

from __future__ import annotations

from torch2vk.runtime.logical import LogicalTensor
from torch2vk.runtime.session import RuntimeSession

from models.omnivoice._frame import OmniVoiceTorchOp
from models.omnivoice.shaders.audio_codec_decoder_conv1d_k1_f32 import (
    OMNIVOICE_AUDIO_CODEC_DECODER_CONV1D_K1_F32,
)
from models.omnivoice.shaders.audio_codec_decoder_conv1d_k7_f32 import (
    OMNIVOICE_AUDIO_CODEC_DECODER_CONV1D_K7_F32,
)
from models.omnivoice.shaders.audio_codec_decoder_deconv1d_block0_f32 import (
    OMNIVOICE_AUDIO_CODEC_DECODER_DECONV1D_BLOCK0_F32,
)
from models.omnivoice.shaders.audio_codec_decoder_quantizer_embed_sum_f32 import (
    OMNIVOICE_AUDIO_CODEC_DECODER_QUANTIZER_EMBED_SUM_F32,
)
from models.omnivoice.shaders.audio_codec_decoder_residual_add_f32 import (
    OMNIVOICE_AUDIO_CODEC_DECODER_RESIDUAL_ADD_F32,
)
from models.omnivoice.shaders.audio_codec_decoder_snake_conv1d_k1_residual_add_f32 import (
    OMNIVOICE_AUDIO_CODEC_DECODER_SNAKE_CONV1D_K1_RESIDUAL_ADD_F32,
)
from models.omnivoice.shaders.audio_codec_decoder_snake_f32 import (
    OMNIVOICE_AUDIO_CODEC_DECODER_SNAKE_F32,
)
from models.omnivoice.tensors.audio_codec import OmniVoiceAudioCodecTensors


AUDIO_CODEC_DECODE_TORCH_OPS = (
    OmniVoiceTorchOp(
        "quantizer_embed_sum",
        ("audio_tokens", "quantizer_embeddings"),
        ("decoder_hidden",),
        "",
    ),
    OmniVoiceTorchOp(
        "decoder_conv_stack",
        ("decoder_hidden",),
        ("decoder_hidden",),
        "",
    ),
    OmniVoiceTorchOp(
        "project_out",
        ("decoder_hidden",),
        ("audio_waveform",),
        "",
    ),
)

AUDIO_CODEC_DECODE_SHADERS = (
    OMNIVOICE_AUDIO_CODEC_DECODER_QUANTIZER_EMBED_SUM_F32,
    OMNIVOICE_AUDIO_CODEC_DECODER_CONV1D_K1_F32,
    OMNIVOICE_AUDIO_CODEC_DECODER_CONV1D_K7_F32,
    OMNIVOICE_AUDIO_CODEC_DECODER_DECONV1D_BLOCK0_F32,
    OMNIVOICE_AUDIO_CODEC_DECODER_SNAKE_F32,
    OMNIVOICE_AUDIO_CODEC_DECODER_SNAKE_CONV1D_K1_RESIDUAL_ADD_F32,
    OMNIVOICE_AUDIO_CODEC_DECODER_RESIDUAL_ADD_F32,
)


def run_omnivoice_audio_codec_decode(
    rt: RuntimeSession,
    tensors: OmniVoiceAudioCodecTensors,
) -> LogicalTensor:
    with rt.frame("omnivoice.audio_codec_decode"):
        OMNIVOICE_AUDIO_CODEC_DECODER_QUANTIZER_EMBED_SUM_F32(
            rt,
            output=tensors.decoder_input,
            audio_ids=tensors.audio_tokens,
            embed0=tensors.quantizer_embed0,
            embed1=tensors.quantizer_embed1,
            embed2=tensors.quantizer_embed2,
            embed3=tensors.quantizer_embed3,
            embed4=tensors.quantizer_embed4,
            embed5=tensors.quantizer_embed5,
            embed6=tensors.quantizer_embed6,
            embed7=tensors.quantizer_embed7,
        )
    return tensors.decoder_input
