# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice audio-head frame scaffold."""

from __future__ import annotations

from torch2vk.runtime.logical import LogicalTensor
from torch2vk.runtime.session import RuntimeSession

from models.omnivoice._frame import OmniVoiceTorchOp, omnivoice_frame
from models.omnivoice.shaders.audio_head_mat_vec_f16_f32_f32 import (
    OMNIVOICE_AUDIO_HEAD_MAT_VEC_F16_F32_F32,
)
from models.omnivoice.shaders.audio_head_matmul_f16_f32_f16acc_large import (
    OMNIVOICE_AUDIO_HEAD_MATMUL_F16_F32_F16ACC_LARGE,
)
from models.omnivoice.shaders.audio_head_matmul_f16_f32_f16acc_small import (
    OMNIVOICE_AUDIO_HEAD_MATMUL_F16_F32_F16ACC_SMALL,
)
from models.omnivoice.shaders.audio_head_round_f32_to_f16_f32 import (
    OMNIVOICE_AUDIO_HEAD_ROUND_F32_TO_F16_F32,
)
from models.omnivoice.shaders.audio_head_scalar_f16_f32_f32 import (
    OMNIVOICE_AUDIO_HEAD_SCALAR_F16_F32_F32,
)
from models.omnivoice.tensors.text import OmniVoiceAudioHeadTensors


AUDIO_HEAD_TORCH_OPS = (
    OmniVoiceTorchOp(
        "audio_head_projection",
        ("hidden_states", "audio_heads_weight"),
        ("audio_logits",),
        "",
    ),
    OmniVoiceTorchOp(
        "reshape_codebooks",
        ("audio_logits",),
        ("audio_logits",),
        "",
    ),
)

AUDIO_HEAD_SHADERS = (
    OMNIVOICE_AUDIO_HEAD_MATMUL_F16_F32_F16ACC_LARGE,
    OMNIVOICE_AUDIO_HEAD_MATMUL_F16_F32_F16ACC_SMALL,
    OMNIVOICE_AUDIO_HEAD_MAT_VEC_F16_F32_F32,
    OMNIVOICE_AUDIO_HEAD_SCALAR_F16_F32_F32,
    OMNIVOICE_AUDIO_HEAD_ROUND_F32_TO_F16_F32,
)


def run_omnivoice_audio_head(
    rt: RuntimeSession,
    tensors: OmniVoiceAudioHeadTensors,
    *,
    pytorch_compare: bool = True,
) -> LogicalTensor:
    del tensors
    frame_scope = omnivoice_frame(
        rt,
        "omnivoice.audio_head",
        pytorch_compare=pytorch_compare,
    )
    with frame_scope:
        raise NotImplementedError("Generated scaffold only: lower AUDIO_HEAD_TORCH_OPS.")
