# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice generation-loop scaffold."""

from __future__ import annotations

from torch2vk.runtime.logical import LogicalTensor
from torch2vk.runtime.session import RuntimeSession

from models.omnivoice.audio_codec_decode import run_omnivoice_audio_codec_decode
from models.omnivoice.audio_head import run_omnivoice_audio_head
from models.omnivoice.text_prefill import run_omnivoice_text_prefill
from models.omnivoice.tensors.audio_codec import OmniVoiceAudioCodecTensors
from models.omnivoice.tensors.text import OmniVoiceTextTensors


def run_omnivoice_generation_loop(
    rt: RuntimeSession,
    text_tensors: OmniVoiceTextTensors,
    audio_codec_tensors: OmniVoiceAudioCodecTensors,
    *,
    num_step: int,
    pytorch_compare: bool = True,
) -> LogicalTensor:
    if num_step <= 0:
        raise ValueError(f"num_step must be positive, got {num_step}")
    run_omnivoice_text_prefill(rt, text_tensors.prefill, pytorch_compare=pytorch_compare)
    run_omnivoice_audio_head(rt, text_tensors.audio_head, pytorch_compare=False)
    del num_step
    return run_omnivoice_audio_codec_decode(rt, audio_codec_tensors)
