# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice input embedding frame scaffold."""

from __future__ import annotations

from torch2vk.runtime.session import RuntimeSession

from models.omnivoice._frame import OmniVoiceFrameStep, omnivoice_frame
from models.omnivoice.shaders.audio_embedding_sum_f32 import OMNIVOICE_AUDIO_EMBEDDING_SUM_F32
from models.omnivoice.tensors.text import OmniVoiceTextPrefillTensors


INPUT_EMBEDDINGS_FRAME_STEPS = (
    OmniVoiceFrameStep(
        "text_embed_lookup",
        ("input_ids", "embed_tokens_weight"),
        ("text_embeds",),
        "",
    ),
    OmniVoiceFrameStep(
        "audio_embedding_sum",
        ("input_ids", "audio_mask", "audio_embeddings_weight"),
        ("audio_embeds",),
        "",
    ),
    OmniVoiceFrameStep(
        "where_audio_mask",
        ("audio_mask", "audio_embeds", "text_embeds"),
        ("inputs_embeds",),
        "",
    ),
)

INPUT_EMBEDDINGS_SHADERS = (OMNIVOICE_AUDIO_EMBEDDING_SUM_F32,)


def run_omnivoice_input_embeddings(
    rt: RuntimeSession,
    tensors: OmniVoiceTextPrefillTensors,
    *,
    pytorch_compare: bool = True,
) -> None:
    del tensors
    frame_scope = omnivoice_frame(
        rt,
        "omnivoice.input_embeddings",
        pytorch_compare=pytorch_compare,
    )
    with frame_scope:
        raise NotImplementedError("Generated scaffold only: lower INPUT_EMBEDDINGS_FRAME_STEPS.")
