# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice iterative masked decode frame scaffold."""

from __future__ import annotations

from torch2vk.runtime.logical import LogicalTensor
from torch2vk.runtime.session import RuntimeSession

from models.omnivoice._frame import OmniVoiceFrameStep, omnivoice_frame
from models.omnivoice.tensors.inference import OmniVoiceIterativeDecodeTensors


ITERATIVE_DECODE_FRAME_STEPS = (
    OmniVoiceFrameStep(
        "initialize_masked_tokens",
        ("target_lens",),
        ("tokens",),
        "",
    ),
    OmniVoiceFrameStep(
        "for_each_decode_step",
        ("batch_input_ids", "batch_audio_mask"),
        ("audio_logits",),
        "",
    ),
    OmniVoiceFrameStep(
        "token_select",
        ("audio_logits", "tokens"),
        ("tokens",),
        "",
    ),
    OmniVoiceFrameStep(
        "update_conditioned_inputs",
        ("tokens",),
        ("batch_input_ids",),
        "",
    ),
)


def run_omnivoice_iterative_decode(
    rt: RuntimeSession,
    tensors: OmniVoiceIterativeDecodeTensors,
    *,
    num_step: int,
    pytorch_compare: bool = True,
) -> LogicalTensor:
    del tensors
    if num_step <= 0:
        raise ValueError(f"num_step must be positive, got {num_step}")
    frame_scope = omnivoice_frame(
        rt,
        "omnivoice.iterative_decode",
        pytorch_compare=pytorch_compare,
    )
    with frame_scope:
        raise NotImplementedError("Generated scaffold only: lower ITERATIVE_DECODE_FRAME_STEPS.")
