# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice reference prompt frame scaffold."""

from __future__ import annotations

from torch2vk.runtime.logical import (
    LogicalTensor,
    MemoryClass,
    TensorLifetime,
    TensorRole,
)
from torch2vk.runtime.session import RuntimeSession
from torch2vk.vulkan.types import TensorSpec

from models.omnivoice._frame import OmniVoiceTorchOp, omnivoice_frame


REFERENCE_PROMPT_TORCH_OPS = (
    OmniVoiceTorchOp(
        "load_or_resample_reference_audio",
        ("ref_audio",),
        ("reference_waveform",),
        "",
    ),
    OmniVoiceTorchOp(
        "audio_tokenizer_encode",
        ("reference_waveform",),
        ("reference_tokens",),
        "",
    ),
    OmniVoiceTorchOp(
        "normalize_reference_text",
        ("ref_text",),
        ("reference_text",),
        "",
    ),
)


def run_omnivoice_reference_prompt(
    rt: RuntimeSession,
    *,
    pytorch_compare: bool = True,
) -> LogicalTensor:
    frame_scope = omnivoice_frame(
        rt,
        "omnivoice.reference_prompt",
        pytorch_compare=pytorch_compare,
    )
    with frame_scope:
        # Placeholder logical output for generated pipeline wiring.
        return LogicalTensor(
            name="omnivoice.reference_prompt.reference_text",
            spec=TensorSpec(dtype="int64", shape=(1, 1)),
            role=TensorRole.OUTPUT,
            memory=MemoryClass.HOST_OUTPUT,
            lifetime=TensorLifetime.FRAME,
        )
