# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice reference prompt frame scaffold."""

from __future__ import annotations

from torch2vk.runtime.logical import LogicalTensor
from torch2vk.runtime.session import RuntimeSession

from models.omnivoice._frame import OmniVoiceFrameStep, omnivoice_frame


REFERENCE_PROMPT_FRAME_STEPS = (
    OmniVoiceFrameStep(
        "load_or_resample_reference_audio",
        ("ref_audio",),
        ("reference_waveform",),
        "",
    ),
    OmniVoiceFrameStep(
        "audio_tokenizer_encode",
        ("reference_waveform",),
        ("reference_tokens",),
        "",
    ),
    OmniVoiceFrameStep(
        "normalize_reference_text",
        ("ref_text",),
        ("reference_text",),
        "",
    ),
)


def run_omnivoice_reference_prompt(
    rt: RuntimeSession,
    *,
    pytorch_compare: bool = True,
) -> LogicalTensor:
    frame_scope = omnivoice_frame(
        rt,
        "omnivoice.reference_prompt",
        pytorch_compare=pytorch_compare,
    )
    with frame_scope:
        raise NotImplementedError("Generated scaffold only: lower REFERENCE_PROMPT_FRAME_STEPS.")
