# This file is generated by torch2vk.export. Do not edit by hand.
"""Generated OmniVoice text/LLM prefill frame scaffold."""

from __future__ import annotations

from torch2vk.runtime.session import RuntimeSession

from models.omnivoice._frame import OmniVoiceFrameStep, omnivoice_frame
from models.omnivoice.tensors.text import OmniVoiceTextPrefillTensors


TEXT_PREFILL_FRAME_STEPS = (
    OmniVoiceFrameStep(
        "input_embeddings",
        ("input_ids", "audio_mask"),
        ("inputs_embeds",),
        "",
    ),
    OmniVoiceFrameStep(
        "llm_layer_loop",
        ("inputs_embeds", "attention_mask"),
        ("hidden_states",),
        "",
    ),
    OmniVoiceFrameStep(
        "final_norm",
        ("hidden_states",),
        ("hidden_states",),
        "",
    ),
)


def run_omnivoice_text_prefill(
    rt: RuntimeSession,
    tensors: OmniVoiceTextPrefillTensors,
    *,
    pytorch_compare: bool = True,
) -> None:
    del tensors
    frame_scope = omnivoice_frame(
        rt,
        "omnivoice.text_prefill",
        pytorch_compare=pytorch_compare,
    )
    with frame_scope:
        raise NotImplementedError("Generated scaffold only: lower TEXT_PREFILL_FRAME_STEPS.")
