# This file is generated by torch2vk.exportv2. Do not edit by hand.
"""Generated OmniVoice text/LLM prefill frame scaffold."""

from __future__ import annotations

from torch2vk.runtime.session import RuntimeSession

from models.omnivoice._frame import OmniVoiceTorchOp
from models.omnivoice.input_embeddings import run_omnivoice_input_embeddings
from models.omnivoice.tensors.text import OmniVoiceTextPrefillTensors


TEXT_PREFILL_TORCH_OPS = (
    OmniVoiceTorchOp(
        "input_embeddings",
        ("input_ids", "audio_mask"),
        ("inputs_embeds",),
        "",
    ),
    OmniVoiceTorchOp(
        "llm_layer_loop",
        ("inputs_embeds", "attention_mask"),
        ("hidden_states",),
        "",
    ),
    OmniVoiceTorchOp(
        "final_norm",
        ("hidden_states",),
        ("hidden_states",),
        "",
    ),
)


def run_omnivoice_text_prefill(
    rt: RuntimeSession,
    tensors: OmniVoiceTextPrefillTensors,
    *,
    pytorch_compare: bool = True,
):
    return run_omnivoice_input_embeddings(
        rt,
        tensors,
        pytorch_compare=pytorch_compare,
        max_ops=None,
    )
